api/bucket.go
Support upload file to bucket.
This will be needed for uploaded windup rule files and binaries associated with applications.
=> Support upload file to bucket.

addon/application.go
Add method to find identity for application and kind.
Common for addons.
=> Add method to find identity for application and kind.

addon/adapter.go, task/manager.go
Fix custom addon volumes not mounted in the container.
=> Addon volumes

api/proxy.go
Fix proxy endpoint field case and GET endpoint 404.
=> Fix proxy endpoint field case and GET endpoint 404.

api/proxy.go, hack/add/proxy.sh, hack/update/proxy.sh, model/proxy.go
Add Proxy: enabled and excluded hosts list.
Also applies new pattern to updates.  Needed to support enabled=0.
=> Add Proxy: enabled and excluded hosts list.

addon/client.go, auth/middleware.go, hack/cmd/addon/secret.json
Fix SEGV setting auth header in NIL Header object.
Use _const_ for header key for better coupling.
=> Fix SEGV setting auth header in NIL Header object.

api/proxy.go, api/stakeholder.go, hack/add/addon-task.sh, hack/add/application.sh, hack/add/bucket.sh, hack/add/business-service.sh, hack/add/job-function.sh, hack/add/proxy.sh, hack/add/review.sh, hack/add/stakeholder-group.sh, hack/add/stakeholder.sh, hack/add/tag.sh, hack/add/task.sh, hack/cmd/addon/main.go
=> Enhanced API compatibility

api/application.go, api/base.go, api/bucket.go, api/proxy.go, hack/add/all.sh, hack/add/bucket.sh, hack/add/proxy.sh, model/application.go, model/bucket.go, model/identity.go, model/proxy.go
Add missing FKs on Proxy and Bucket.  Added additional (relation) fields apparently needed by GORM to generate the FK constraints.
Add _Resource_ methods:
- ref(uint, Named)
- refPtr(*uint, Named)
- idPtr(*Ref)
=> Add missing FKs on Proxy and Bucket.

api/application.go, api/taskgroup.go, hack/cmd/addon/main.go, model/task.go
Tasks within a group share the same bucket.
Also but unrelated, the Application facts should be initialized. This makes working with them so much easier.
=> Tasks: shared bucket when in a group.

README.md
- Add badge to display status of quay image
=> Add quay.io status badge

hack/update/setting.sh, model/setting.go
=> Fix PUT on settings.

api/adoptionplan.go, api/pkg.go, hack/add/dependency.sh, hack/add/review.sh
Generates an app dependency graph and sorts it into topological
order, assigning weights based on the effort of each app's
most expensive chain of dependencies.
=> Add AdoptionPlan handler

settings/hub.go, task/manager.go
Running into issues running jobs/tasks on some minikube installations.
Unrelated: reducing the task retry to (1).
=> Run task jobs with hub SA.

addon/adapter.go, addon/client.go, addon/error.go, hack/cmd/addon/main.go
Better support for _soft_ errors that are not stack traced.
Refactored addon errors in to separate file.
=> Better support for addon soft errors.

api/application.go, api/group.go, api/stakeholder.go, model/application.go
Need to delete all associations else FK constraint violation.
Also, needed cascade delete.
=> Fix application delete.

addon/client.go
The addon should not fail due to the hub API temporarily not available due to restart or network disruption.
Added the explicit transport configuration.
=> Addon client Resiliant to hub availability.

api/group.go, hack/update/stakeholder-group.sh
Fixes https://issues.redhat.com/browse/TACKLE-450
=> Fix stakeholder group update.

settings/auth.go
Reverts konveyor/tackle2-hub#51
Causing some RBAC issues.
=> Revert "Require auth by default"

api/import.go, importer/manager.go, model/application.go, model/identity.go
Taking over Sam's PR https://github.com/konveyor/tackle2-hub/pull/52/ incorporating Jeff's feedback.
This PR extends Application CSV import.
Example CSV file (uses relations to objects created by scripts in hack/add directory), named imp.csv
```
Applications (First line is header)
1,MarketingApplication,My cool app,No comment,Marketing,binarygrp,elfbin,v1,rpm,url,branch,path,Testing,RHEL
```
Upload
```
curl -F "file=@imp.csv" localhost:8080/importsummaries/upload
```
Get imports
```
curl localhost:8080/imports
```
Note: failed binary fields validation sets ```"errorMessage":"Binary-related fields for application MarketingApplication need to be all present or all empty"``` on Import (e.g. if removed "v1" from csv above)
Get applications
```
curl localhost:8080/applications
```
=> Update Application CSV import Add repo, binary

api/import.go, importer/manager.go, model/application.go
Adding RepositoryKind into Application CSV Import and using 'git' as a
default value.
=> Set default RepositoryKind in Application Import

tasking/manager.go
Add Task.State=Pending to reflect pod pending phase.
=> Add Task.State=Pending to reflect pod pending phase.

addon/task.go, api/task.go, model/task.go, tasking/manager.go
Support task priorities and addon attaching data.
Needed to support https://github.com/konveyor/tackle2-addon/pull/1
=> Support task priorities.

api/task.go, tasking/manager.go, tasking/reaper.go
Refactor pod delete relocated to the _Runtime_ tasking.Task object for symmetry proper better ownership of concerns.
Doing this in preparation for following PR to implement task Cancel.
=> Refactor pod delete.

.gitignore, hack/tool/README.md, hack/tool/tackle, hack/tool/tackle-config.yml.example
Follow-up PR to https://github.com/konveyor/tackle2-hub/pull/71 fixing example config for tackle CLI tool.
Putting to draft, going to add few fixes related export/import script for not trivial records in database.
=> Update tackle CLI tool for data migration

api/application.go
- Instead of adding a custom validation for git urls, rely on the ui field level validation.
=> Remove url validation

api/import.go
Updating fields for CSV application import error message for invalid CSV
format to be correctly read and displayed by UI.
Thanks Ian for help on UI side!
=> Updating CSV import error message for UI

api/import.go
Beta backport of https://github.com/konveyor/tackle2-hub/pull/89
Updating fields for CSV application import error message for invalid CSV
format to be correctly read and displayed by UI.
=> [BACKPORT] Updating CSV import error message for UI

api/import.go
Updated dependency parsing to ignore columns following Depedency and
Dependencyirection fields in CSV.
=> Fix CSV dependencies import

hack/tool/README.md, hack/tool/tackle
To reduce the amount of information in the log.
=> Allow skipping ssl warnings for requests

hack/tool/README.md, hack/tool/tackle
Ignore failed uploaded item (due to request failed) and move to the next item
=> Ignore import error

api/application.go, api/bucket.go, api/task.go, api/taskgroup.go
Add support for DELETE on bucket endpoints.
Fix api docstrings.
Prevent operations on buckets after bucket released.
=> Add support for DELETE on bucket endpoints.

model/control.go
Fix http-500 deleting job funcions.
https://issues.redhat.com/browse/TACKLE-633
=> TACKLE-633: Add ON DELETE SET NULL to stakeholder FK => job function.

task/manager.go
=> Adjust task labels.

api/base.go, auth/middleware.go, auth/provider.go
Fix SEGV in provider when token is invalid.
Add support for special task token.
=> Fix SEGV in provider and support special task token.

api/application.go, api/businessservice.go, api/group.go, api/stakeholder.go, api/task.go, model/application.go, model/control.go, model/identity.go, model/proxy.go
https://issues.redhat.com/browse/TACKLE-638
https://issues.redhat.com/browse/TACKLE-643
Review of foreign key constraints.
```
CREATE TABLE `Setting` (`ID` integer,
`CreateTime` datetime,
`CreateUser` text,
`UpdateUser` text,
`Key` text,
`Value` JSON,
PRIMARY KEY (`ID`));
CREATE TABLE `ImportSummary` (`ID` integer,
`CreateTime` datetime,
`CreateUser` text,
`UpdateUser` text,
`Content` blob,
`Filename` text,
`ImportStatus` text,
PRIMARY KEY (`ID`));
CREATE TABLE `Import` (`ID` integer,
`CreateTime` datetime,
`CreateUser` text,
`UpdateUser` text,
`Filename` text,
`ApplicationName` text,
`BusinessService` text,
`Comments` text,
`Dependency` text,
`DependencyDirection` text,
`Description` text,
`ErrorMessage` text,
`IsValid` numeric,
`RecordType1` text,
`ImportSummaryID` integer,
`Processed` …
```
=> Fix ON DELETE constraints.

api/application.go
https://issues.redhat.com/browse/TACKLE-673
Add support for application delete.
=> TACKLE-673: Add support for application bulk delete.

hack/tool/tackle
There was a bug with import/export tool exporting Stakeholders and their connection to StakeholderGroups, fixed.
=> Fix tool export Stakeholders

api/import.go, importer/manager.go, model/application.go
Updating CSV import adding an optional field "createEntities" (true by
default) to create missing BusinessServices,TagTypes and Tags in the Hub database.
https://issues.redhat.com/browse/TACKLE-691
https://issues.redhat.com/browse/TACKLE-693
=> CSV import createEntities

importer/manager.go
Updating CSV application import code to count with optional relation Application-BusinessService (instead of mandatory).
Related to: https://github.com/konveyor/tackle2-hub/pull/136
=> Update CSV import to optional BusinessService

api/pkg.go, api/schema.go
Backport https://github.com/konveyor/tackle2-hub/pull/151
=> [backport-2.1.2] Add /schema endpoint.

database/db_test.go, database/pkg.go
backport: https://github.com/konveyor/tackle2-hub/pull/154
=> [backport-2.1.2] Tackle-654: Better support DB concurrency.

importer/manager.go
2.1.2 backport of https://github.com/konveyor/tackle2-hub/pull/140
Updating CSV application import code to count with optional relation Application-BusinessService (instead of mandatory).
=> [Backport 2.1.2] Update CSV import to optional BusinessService

hack/add/all.sh, hack/add/bucket.sh, hack/add/login.sh, hack/add/settings.sh
=> hack curl additions

auth/provider.go
Signed-off-by: Sam Lucidi <slucidi@redhat.com>
=> Fix pointer and ID issues while creating a Role for the first time

auth/provider.go, settings/auth.go
Related to https://github.com/konveyor/tackle2-operator/pull/128
Signed-off-by: Sam Lucidi <slucidi@redhat.com>
=> Make resetting Keycloak user password optional

.github/workflows/main.yml, .github/workflows/test-addons.yml, Makefile
Gate PRs to main #169
Test windup addon #170
=> Build hub and install in tackle + test windup addon 

addon/client.go
Addon binding client improvements mainly focused on supporting addon writers running the addon locally.
- Add `Accept` header to avoid 502 by nginx reverse proxy when Accept not set.  Helpful for addon development.
- Append the endpoint path to the Hub URL path instead of overwriting it. Need for Helpful for addon development which needs to set HUB_BASE_URL to the route/ingress:  Eg: http://192.168.49.2/hub.  The /hub needs to be preserved.
- Set the token in the Authentication header in send(). Duplicated.
- Fix logic in send when and error is returned by `client.Do()`.  Fixes SEGV.
=> Addon binding client improvements.

api/auth.go, api/pkg.go, auth/builtin.go, auth/keycloak.go, auth/provider.go, hack/add/login.sh
Re: #197 Adds /auth/login to obtain bearer token.
POST body {"user": "", "password": ""}
Returns: token.
=> Adds /auth/login to obtain token.

docs/docs.go, docs/swagger.json, docs/swagger.yaml
Updating Swagger API spec files with recent hub API changes including Jira integration, Application/Tag subresource and Auth token creation via API.
- https://github.com/konveyor/tackle2-hub/pull/203
- https://github.com/konveyor/tackle2-hub/pull/205
- https://github.com/konveyor/tackle2-hub/pull/207
Signed-off-by: Marek Aufart <maufart@redhat.com>
=> Update swagger API spec files

auth/role.go, auth/roles.yaml
Add applications.tags (sub-resource) scopes to roles.
=> Add applications.tags scopes.

api/identity.go, api/pkg.go
Signed-off-by: Sam Lucidi <slucidi@redhat.com>
=> Fix formatting

hack/tool/README.md
Updating CLI tool requirements for crypto package and updates on Tackle 2 export usage steps.
Fixes: https://github.com/konveyor/tackle2-hub/issues/222 reported by @ibragins 
Signed-off-by: Marek Aufart <maufart@redhat.com>
=> :book: Update tool README with requirements

migration/v3/seed/main.go
Fix empty ruleSet in _category_ bundles.
Made sure all of the seeded RuleSets had names to conform to the unique constraint on RuleSet.Name+RuleBundleID.
=> :ghost: Fix seeded bundles.

migration/v2/model/application.go, migration/v2/model/pkg.go, migration/v2/model/proxy.go, migration/v2/model/setting.go, migration/v2/model/task.go, migration/v2/model/taskgroup.go, migration/v2/model/taskreport.go, migration/v3/model/application.go, migration/v3/model/fact.go, migration/v3/model/pkg.go, migration/v3/model/rulebundle.go, migration/v3/model/ruleset.go, migration/v3/model/ticket.go, migration/v3/model/tracker.go
=> :bug: Fix number as json root; custom json field no longer used.

api/setting.go, hack/add/settings.sh
Fixes https://github.com/konveyor/tackle2-hub/issues/234
=> :sparkles: Allow creating settings by key

api/application.go, api/bucket.go, api/file.go, api/setting.go, docs/binding.txt, docs/docs.go, docs/swagger.json, docs/swagger.yaml
Updating swagger files to be up-to-date 2023-03-02 including changes from:
- https://github.com/konveyor/tackle2-hub/pull/226
- https://github.com/konveyor/tackle2-hub/pull/245
- https://github.com/konveyor/tackle2-hub/pull/246
- https://github.com/konveyor/tackle2-hub/pull/249
=> :book: Update swagger OpenAPI spec

importer/manager.go
The import manager was preloading the `TagCategory` relationship for Tags, but the association field is named `Category`. This was causing Categories to not be preloaded on the Tag models, which makes imports fail. (either by failing to find the category and giving up, or by trying to recreate the already-existing category depending on whether `createEntities` is enabled.). 
This change fixes import of tagged application by preloading the right association, and ensuring that ApplicationTag associations are created properly. I also took the opportunity to simplify (to my eyes) some of the variable naming.
=> :bug: Fix broken import of tagged applications

migration/v3/seed/main.go
Closes the hub portion of https://issues.redhat.com/browse/MTA-267
=> :seedling: Add eap8 target as option in seeded data

addon/adapter.go, addon/application.go, addon/client.go, addon/file.go, addon/identity.go, addon/proxy.go, addon/rulebundle.go, addon/setting.go, addon/tag.go, addon/task.go
Adds Path object for more intuitive syntax.
=> :ghost: Adds Path object for more intuitive syntax.

importer/manager.go
=> :ghost: [Backport] import: don't generate color for new TagCategories

tracker/manager.go
Fixes https://github.com/konveyor/tackle2-hub/issues/300
=> :bug: Fix Jira connection test nil ptr dereference

api/bucket.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
A tiny fix of Bucket put spec in swagger (```//buckets/...``` -> ```/buckets/...```) and swagger files regeneration.
Related to Maayan's/QE question on buckets upload.
=> :book: Tiny bucket swagger doc update

addon/application.go, api/analysis.go, api/application.go, api/base.go, api/bucket.go, api/error.go, api/filter/error.go, api/filter/filter.go, api/filter/filter_test.go, api/filter/lexer.go, api/filter/parser.go, api/filter/pkg.go, api/pkg.go, api/proxy.go, database/pkg.go, hack/add/all.sh, hack/add/analysis.sh, migration/v4/migrate.go, migration/v4/model/analysis.go, migration/v4/model/application.go, migration/v4/model/pkg.go, model/pkg.go
Add models/APIs for analysis _reports_.
Adds _filter_ support.
Adds X-Total response header to support pagination in the UI.
Todo: 
Iteration of: https://github.com/konveyor/tackle2-hub/issues/266
=> Analysis report.

migration/v3/seed/main.go
https://issues.redhat.com/browse/MTA-468
=> :bug: Update seeded rulebundle description for Azure

migration/v3/seed/main.go
https://issues.redhat.com/browse/MTA-468
=> :bug: [backport] Update seeded rulebundle description for Azure (#319)

binding/application.go, binding/bucket.go, binding/richclient.go, test/README.md, test/api/client/client.go, test/integration/applications-inventory/analysis/pkg.go, test/integration/applications-inventory/analysis/windup_basic_test.go
Few updates on tests:
- added Get/Put Bucket methods to binding
- updated login env variables and README for tests (tested and works with auth enabled)
- added simple analysis report content check in integration tests (to be moved, but for now it's here)
=> :seedling: Update tests bucket, login, integration

tracker/jira/connector.go
Fixes an inconsistency in the API.
=> Use IDs for Jira projects and issue types

api/analysis.go, migration/v4/model/analysis.go, migration/v4/model/pkg.go, model/pkg.go
=> Analysis prefix on models and resources removed.

hack/add/analysis.sh
Adds a code snip for the first 5 incidents.
Makes the number of generated incidents configurable.
Makes each the issue name unique by ruleset and rule.
=> :ghost: Add code snip to hack analysis.

.github/workflows/swagger-change-notification.yml
Related to https://issues.redhat.com/browse/MTA-615
=> :ghost: Add swagger spec change notification for QE

api/analysis.go
=> :sparkles: File report filter

task/manager.go
=> :bug: Discard not-found error when reaping tasks.

Makefile, hack/next-migration.sh
Add script and make target to generate the next migration.
To run:
```
$ make migration
```
=> :ghost: Automate creating the next (empty) migration.

docs/test-api-matrix.md, test/api/dependency/api_test.go, test/api/dependency/samples.go
Follow up PR for  #370 
- added tests for cross dependency check 
- Updated `test-api-matrix.md`
=> :seedling: add cross dependency test

migration/v2/model/identity.go, migration/v4/migrate.go, migration/v4/model/identity.go, migration/v4/model/pkg.go, test/api/identity/api_test.go
Adding uniq Name constraint to Identity model. The constraint is enforced regardless Identity Kind in similar way as UI do for a while.
Fixes: https://issues.redhat.com/browse/MTA-27
=> :bug: Add uniq Name constrain to Identity

api/tracker.go
=> :bug: Fix Tracker API resource allowed kinds (#394)

api/base.go
Fixes https://github.com/konveyor/tackle2-hub/issues/397
=> :bug: make Resource.nameOf return what it finds

hack/add/analysis.sh
Making incident mock data look a little more real for the UI demo
=> :ghost: Hack analysis: Add .java file extension and example markdown incident message for UI use

api/analysis.go
Filter on  businessService.name not wired up correctly.
Added by ID.
=> :bug: Fix filter by businessService name; and id.

task/manager.go
Fixes https://issues.redhat.com/browse/MTA-894
=> :bug: metrics: only count the first time a task starts

hack/add/analysis.sh, migration/v3/seed/main.go
Resolves https://issues.redhat.com/browse/MTA-483
=> :bug: Remove EAP6 target

hack/add/analysis.sh, migration/v3/seed/main.go
Back-port #448 to release-0.2.
=> :bug: [release-0.2] Remove EAP6 target

tracker/manager.go
=> :bug: [release-0.2] Only create connector once to fix ident mangling

binding/richclient.go, binding/tracker.go, docs/test-api-matrix.md, test/api/tracker/api_test.go, test/api/tracker/pkg.go, test/api/tracker/samples.go
=> :seedling: add tracker API Test

api/analysis.go
=> :ghost: Using CreateTemp().

api/archetype.go, migration/v9/model/archetype.go
* Adds cascading deletes to archetype tag relationships
* Surfaces the Review relationship in the archetype resource
* Removes some dead code
=> :bug: Fix constraints on archetype tag rels

api/archetype.go
Fixes [https://issues.redhat.com/browse/MTA-1330](https://issues.redhat.com/browse/MTA-1330?filter=-1)
=> :sparkles: Add `assessed` field to Archetype REST resource

api/application.go, api/archetype.go
Fixes https://github.com/konveyor/tackle2-hub/issues/510
=> :bug: Increment assessment counter when a new one is created

api/analysis.go
https://issues.redhat.com/browse/MTA-1298
=> :bug: Fix business service filter of issues.

go.mod, go.sum
=> :ghost: Update 0.1.2 for License.

api/archetype.go
This was missed in the original PR. #544
=> :ghost: Preload Archetype assessment stakeholder relations

assessment/tag.go
Fixes an issue which is causing assessment tag autoapply and question include/exclude to fail.
=> :bug: Fix ptr-to-loopvar bug in assessment tags module

docs/test-api-matrix.md
Minor update in API test matrix to keep it up-to-date.
=> :book: Update API test matrix

model/pkg.go
Should be aliased from the model.
=> :bug: Fix json export.

api/migrationwave.go
Fixes https://issues.redhat.com/browse/MTA-1726
=> :bug: [MTA-1726] Migration Waves: require start and end date, require end > start

api/analysis.go
Return empty list of issues when no latest analysis. But still 404 when application not found.
https://issues.redhat.com/browse/MTA-2047
=> :bug: Return empty list when latest analysis does not exist.

api/analysis.go
Return empty list of issues when no latest analysis. But still 404 when application not found.
https://issues.redhat.com/browse/MTA-2047
=> :bug: [backport] Return empty list when latest analysis does not exist. (#602)

api/migrationwave.go
Fixes https://issues.redhat.com/browse/MTA-1726
=> :bug: [Backport][MTA-1726] Migration Waves: require start and end date, require end > start (#604)

hack/tool/tackle
0.3 backport of https://github.com/konveyor/tackle2-hub/pull/615
=> :seedling: [backport] Update export/import tool for Konveyor 0.3 #615

.github/workflows/pr-closed.yaml
Updating secrets for this github action like https://github.com/konveyor/tackle2-ui/pull/1759
=> :seedling: Fix gh cherry-pick action secret

api/application.go, api/archetype.go, assessment/pkg.go
https://issues.redhat.com/browse/MTA-2308
=> :sparkles: Add unassessed risk type and exit early for app risk status calculation

binding/tag.go, binding/tagcategory.go, test/api/tag/api_test.go, test/api/tagcategory/api_test.go
_Look-and-See_ logic replaced to support concurrent operations.
=> :bug: Fix concurrent tag/category Ensure().

auth/auth_test.go
Fix auth unit tests broken by: https://github.com/konveyor/tackle2-hub/pull/621.
=> :ghost: Fix auth tests

addon/adapter.go, auth/builtin.go, auth/builtin_test.go, binding/client.go, binding/richclient.go
auth tech debt improvements.
binding.client tech debt improvements.
=> :ghost: builtin auth test and binding client tech-debt.

migration/v14/migrate.go
Required by: https://github.com/konveyor/tackle2-addon-analyzer/pull/97
=> :sparkles: Add mvn:// prefix to application.binary.

task/manager.go
Just moved a few between the const for state and event.
Corrected the comment.
=> :ghost: task state/event house-cleaning.

hack/add/task.sh, migration/v14/migrate.go
Ensure analyzer tasks created prior to upgrade have kind assigned.
The UI relies on this for correlation with applications.
=> :sparkles: Ensure analyzer tasks created prior to upgrade have kind assigned.

task/manager.go
Reverts konveyor/tackle2-hub#683
=> Revert ":bug: Fix detect container 1+ image pull errors."

migration/v14/model/core.go
Reverts konveyor/tackle2-hub#679
=> Revert ":bug: Add index on Task.ApplicationID."

task/manager.go
Reverts konveyor/tackle2-hub#678
=> Revert ":bug: Detect image issues."

k8s/api/tackle/v1alpha2/zz_generated.deepcopy.go, reaper/bucket.go, reaper/file.go, reaper/ref.go
Reverts konveyor/tackle2-hub#676
=> Revert ":sparkles: Reaper optimization."

hack/add/task.sh, migration/v14/migrate.go
Reverts konveyor/tackle2-hub#674
=> Revert ":sparkles: Ensure analyzer tasks created prior to upgrade have kind assigned."

api/application.go, api/base.go, api/identity.go, api/task.go, api/taskgroup.go, cmd/main.go, importer/manager.go, k8s/api/tackle/v1alpha2/task.go, migration/json/fields.go, migration/json/pkg.go, migration/v14/model/core.go, model/pkg.go, settings/hub.go, task/error.go, task/manager.go, test/api/task/api_test.go, trigger/application.go, trigger/identity.go, trigger/pkg.go
Reverts konveyor/tackle2-hub#685
=> :ghost: Revert "Revert ":ghost: Tasking find refs""

hack/add/task.sh, migration/v14/migrate.go
Reverts konveyor/tackle2-hub#686
=> :ghost: Revert "Revert ":sparkles: Ensure analyzer tasks created prior to upgrade have kind assigned.""

k8s/api/tackle/v1alpha2/zz_generated.deepcopy.go, reaper/bucket.go, reaper/file.go, reaper/ref.go
Reverts konveyor/tackle2-hub#687
=> :sparkles: Revert "Revert ":sparkles: Reaper optimization.""

migration/v14/model/core.go
Reverts konveyor/tackle2-hub#689
=> Revert "Revert ":bug: Add index on Task.ApplicationID.""

addon/task.go
Reverts konveyor/tackle2-hub#690
=> Revert "Revert ":sparkles: Support task addon succeeded with errors.""

task/manager.go
Reverts konveyor/tackle2-hub#691
=> Revert "Revert ":bug: Fix detect container 1+ image pull errors.""

api/sort/sort.go
https://issues.redhat.com/browse/MTA-2432
=> :bug: Sort with COLLATE NOCASE.

api/analysis.go
Fixes https://issues.redhat.com/browse/MTA-3209
=> :bug: MTA-3209 fix effort on app-issues report.

auth/roles.yaml
Add missing scope.
https://issues.redhat.com/browse/MTA-3195
=> :bug: Add task.patch.

seed/target.go, seed/target_test.go
Support: https://issues.redhat.com/browse/MTA-4406
=> :sparkles: Unwanted seeded targets removed.

trigger/identity.go
Fetch application with identity to get the list of applications.
fixes https://issues.redhat.com/browse/MTA-5121
=> :bug: fix identity change trigger.

addon/adapter.go, api/application.go, api/pkg.go, api/platform.go, auth/role.go, auth/roles.yaml, binding/platform.go, binding/richclient.go, migration/v18/model/application.go, migration/v18/model/pkg.go, migration/v18/model/platform.go, model/pkg.go, test/api/manifest/api_test.go, test/api/platform/api_test.go, test/api/platform/pkg.go, test/api/platform/samples.go, test/assert/equality.go
Add support for _source_ platforms.  A platform represents a platform on which an application is deployed.
closes #809
=> :sparkles: Add platform support.

api/analysis.go
This reverts commit a8f955f0148c81c506b19464f3e3f92601afbeb6.
=> :ghost: Revert 773 on release-0.7

api/application.go
=> :bug: Fix application list again.
