api/application.go
hack/add/application.sh
model/application.go

Add Application.Extensions to support application _type_ specific properties.
Needed for MVN coordinates for java application binaries.
Also, suggested that it would be useful for plugins to augment the application with information not suitable for buckets.

Add application extensions.

---

api/application.go
api/base.go
api/identity.go
hack/add/all.sh
hack/add/application.sh
hack/add/identity.sh
model/identity.go

Better support managing app-identity associations.
Identities are _many-2-many_ with applications.  They need to be managed like:
1. create identities.
2. create applications with identity FKs listed.
and/or
2. update application with updated identity FKs listed.
The association needs to be managed from the application.  Essentially, manage the association like we do for Tags.
---
Adds `Ref` for FKs.

Better support managing app-identity associations.

---

addon/adapter.go
settings/addon.go
task/manager.go

addon: use workingDir as home.
The workingDir will be a mounted volume.  We don't want to depend on the elasticity of the _tmpfs_.
This also needs to be the _home_ directory because some CLI tools write files to $HOME by default.

addon: use workingDir as home.

---

api/base.go
api/identity.go
api/task.go
hack/delete/application.sh
hack/update/identity.sh
model/base.go
model/identity.go
model/task.go

When using db.Updates(), the hooks are not fired which in this case is really bad since the BeforeSave() ensures fields are encrypted.
Also revert part of https://github.com/konveyor/tackle2-hub/pull/6.  Somehow, the changed $HOME was not respected by maven.  Found a simpler approach.
Add `Handler.fields()` method using to build a _map_ of a model's fields.  Considered adding `BaseModel.Map()` but since go does not support polymorphism, The receiver IsA BaseModel not the concrete type.
Refit the TaskHandler.Update() to use fields().

Fix identity updates.

---

api/base.go

The pk() is a convenience for getting the `ID` parameter as an integer. This will be useful for update methods that need to coerse the model.ID which is needed for Association methods and eliminates the need to set using _Where_.

Add BaseHandler methods: pk() and fix fields().

---

api/application.go
model/application.go

The UI should consider storing information about the status of _Analyzed_ as a fact instead of searching for tasks. 
Imagined workflow:
1. UI creates an application with fact: _analyzed_=false.
2. User press [analyze] button.
3. UI Launch task.
4. Windup addon sets the _analyzed_=true.
In the table, the UI can simply reflect the value of the Application.Fact.Analyzed instead of correlating with the task status.

Appliation.Extensions concept renamed: Facts.

---

addon/task.go
api/task.go

Addon adapter delete task report when started.
Normally the task report will not exist (in the wild) but this is really useful for repeatedly running addons locally during development.

Addon adapter spams hub log with harmless conflict errors.

---

addon/task.go
api/application.go
api/bucket.go
api/task.go
api/taskgroup.go
hack/add/task.sh
hack/cmd/addon/main.go
hack/cmd/addon/secret.json
model/application.go
model/bucket.go
model/pkg.go
model/task.go
settings/hub.go
task/manager.go

This PR introduces the (optional) relationship between tasks and applications as a first class concept. This includes cascade delete to delete tasks when the associated application is deleted. 
---
Adds missing Application.Binary (string) field.
---
Adjust task/group bucket reaper:
Purge task (buckets) when:
- The task not in a group.  (not shared)
- The task has been terminated for a defined period.
Delete tasks when:
- Not associated with an application.
- The task has never been submitted or terminated for a defined period.
Delete group when:
- The group is empty for a defined period.
Purge group bucket when:
- All of the tasks (buckets) would have been purged had they not been in the group.
--- 
Renamed the model _mixin_ Bucket => BucketOwner and field Path => Bucket because Path is …

Add Task.Application as optional FK.

---

addon/setting.go

This got missed when the API changed to return the value for /settings/<key>.

Fix addon settings API to match rest-api.

---

api/application.go
api/stakeholder.go
hack/update/application.sh

I have been bitten by this before.  Even though the DB object is designed to be chained, you cannot do more than 1 _finisher_ method. Subsequent uses can do weird things due to the DB having inconsistent state.  For example, the DB.table and DB.model may not match.  I have observed this.
fixes #42

Fix PUT on application.

---

api/identity.go
model/identity.go

Encrypt() needs to be called before h.fields() because the hooks are called by db.Updates().
Simplified the idempotent behavior of both Encrypt() and Decrypt() by moving the clearing of the encrypted fields to the hooks.
Explicitly call Encrypt() in the handler Create() and Update() leaving the hooks to perform an Encrypt() as a safety net.  This will result in the Encrypt() being called twice but this is harmless.

Fix identity update.

---

api/identity.go

Render identity fields masked with '*' instead of ''.  This preserves which fields are populated (and not).
This is needed by the UI.

Render identity fields masked with '*' instead of ''. 

---

model/task.go

Fix taskgroup.data propagated to task when task.data is nil.

Fix taskgroup.data propagated to task when task.data is nil.

---

api/identity.go

The Model() method needs to populate the `Encrypted` field for decryption.  This is safe because the API handler always calls Identity.Encrypt() which overwrites the `Encrypted` field before CREATE & UPDATE.
This is a regression introduced a bit ago in the hub but not caught until I rebased the windup addon.
Background on design patterns:
The Resource.Model() method is used to build a DB model.
The Resource.With() method is used to populate the rest Resource with the DB model.

Fix addon identity decryption.

---

addon/client.go
cmd/main.go
importer/manager.go
k8s/client.go
model/bucket.go
model/identity.go
model/task.go

The design pattern used on MTV and other projects has been to Wrap errors at the edge (where they occur).  The wrap method will capture the stack trace and provide for attaching additional context to the error.  The error is returned. The error is either handled or returned on up the stack by the calling code. Should the error never be handled, it will be logged with the relevant stack trace and attached context.

Wrap errors at the edge to capture stack trace.

---

Makefile
addon/adapter.go
addon/task.go
api/task.go
api/taskgroup.go
cmd/main.go
hack/add/task.sh
hack/cmd/addon/main.go
model/bucket.go
model/task.go
settings/hub.go
tasking/manager.go
tasking/reaper.go

Added task job reaper.
Add: serialize tasks running against the same addon & application.
Refactor reapers into separate objects in a new `reaper.go`.
Replaced _purge_ terminology with _empty_ (verb).
Renamed `task` package => `tasking`.
Tasks using Pods (instead of Jobs).
Fix issue with using task _name_ for the pod name.
The operator can override here: https://github.com/konveyor/tackle2-operator/issues/47.
closes #40 
closes #63

Refactor task manager and reaper.

---

addon/task.go
api/task.go
model/task.go
tasking/manager.go

Task.isolated replaced with policy=Isolated. This will be more flexible. 
Policies:
- "" -  The (default) normal concurrent execution.
- Isolated - Must be the only task running.
Added Task.Variant.  The _variant_ signals to the addon (adapter) -_what kind of task_ .  
This will be useful for cases like: Asking the windup adapter to clear the shared maven .m2 repository (instead of run windup).  The reason the variant is a first class concept on the task is because it determines the required `Data` payload.
Perhaps something like:
```
switch addon.Variant() {
case "windup.run", "":
runWindup()
case "maven.clean":
maven := Maven{}
maven.Clean()
default:
err = &SoftError{Reason: "Variant not supported."}
}
```

Support task variants.

---

addon/application.go
addon/identity.go
api/identity.go
model/identity.go
settings/auth.go

Identity fields encrypted instead of entire object.  The primary goal is to provide _natural_ round-trip of resources that reflects the true state.  For example, when edited by the UI, the populated fields can be depicted as populated either by displaying the raw encrypted values (or masked using a password widget).  Then, PUT back with a mix of encrypted (unedited) and clear-text (edited) fields.
```
[
{
"id": 1,
"createUser": "",
"updateUser": "",
"createTime": "2022-04-28T04:15:20.625532011-07:00",
"kind": "git",
"name": "test-git",
"description": "Forklift",
"user": "userA",
"password": "HhVQQNHxrKJLrrRWfJEqIUGdj+jq2wKidQ==",
"key": "PAEYeqPPFKhx+Jvp4WyHZwxNKQo=",
"settings": "ufvqyWVDeTJTuvY6Q7Sma/2HBjlA/UAQUA=="
},
{
"id": 2,
"createUser": "",
"updateUser": "",
"createTime": …
```

Identity fields encrypted instead of entire object.

---

model/task.go
tasking/manager.go

Fix task/secret name for k8s.  Make them based on Task.ID instead of Task.Name.
Add missing error reporting.
Add missing index on Task.State.

Fix task/secret name for k8s.

---

tasking/manager.go
tasking/reaper.go

Fix a few leaks:
- The TaskReport not being deleted in the DB when the Reaper deletes tasks.
- The task's secret is not deleted when the task is deleted by Reaper & API.  Added ownerRef.
- The secret or pod can be leaked depending on where the task manager fails to create resources.

Fix task leaks

---

api/taskgroup.go
cmd/main.go

Taskgroup DELETE without transaction: fixes `database locked` trace.
The sqlite3 database can encounter "database locked" error when using transactions.  The ORM (gorm) does not protect against this known limitation.
Also, noticed when testing that using the signals package to get the _stop channel_ for the manager makes killing the manager in the debugger annoying.  Not really needed since we don't ever plan to stop the manager.

Taskgroup DELETE without transaciton: fixes database locked.

---

api/import.go

Adding check for CSV row length to ensure old Application Import CSV files import fails gracefully. Currently accepted CSV format was introduced in https://github.com/konveyor/tackle2-hub/pull/74 with UI sample https://github.com/konveyor/tackle2-ui/pull/148
https://issues.redhat.com/browse/TACKLE-560

Fix invalid Application Import CSV format error

---

api/import.go

Dependencies were defined in Dependency and DependencyDrection columns in Tackle1.2, the new implementation moved dependencies to own lines (RecordType=2).
Re-adding dependency columns to Application line CSV format (and keeping own lines for dependencies too).
Related to https://github.com/konveyor/tackle2-hub/pull/74

Add inline Application dependency to CSV import

---

task/manager.go

Run task with security context runAsUser:0 (root) on OCP.
This is needed so addon SSH component can create `/etc/ssh/known_hosts`  Also, make troubleshooting MUCH easier when ssh(ing) to the pod.  The injected (generated) user on OCP is a pain.
This is only need for OCP.
Requires: https://github.com/konveyor/tackle2-operator/pull/79

Run task with security context runAsUser:0 (root) on OCP.

---

Dockerfile

- ubi8 base images cut at 8.4 which has not been updated in 6 months , use latest

Refresh ubi base images

---

hack/tool/README.md
hack/tool/tackle

Update of the tackle command line tool bringing changes below:
- export and import full assessment questionnaires
- removes resources not used in Tackle 1.2 (proxy and identity)
- minor updates in readme and related files
https://issues.redhat.com/browse/TACKLE-623

Update tackle CLI tool with Assessments and related fixes

---

api/pathfinder.go
api/pkg.go

Add /assessments endpoint to be rev-proxied to pathfinder.
This is a short-term solution to be improved later by either:
- re-implement assessment (pathfinder) in tackle hub.
- make pathfinder an addon.
This requires PRs in the:
- The UI needs to its rev-proxy to route to the hub.
- The operator needs to define the PATHFINDER_URL in the hub pod.

Add /assessments endpoint as rev-proxy to path finder.

---

api/application.go
api/base.go
api/businessservice.go
api/dependency.go
api/group.go
api/identity.go
api/import.go
api/jobfunction.go
api/proxy.go
api/review.go
api/setting.go
api/stakeholder.go
api/tag.go
api/tagtype.go
api/task.go
api/taskgroup.go
api/volume.go
auth/provider.go

Extending auth provider to get current User's username (```preffered_username``` field from JWT token generated by Keycloak) and setting CreateUser and UpdateUser attributes on models in create&update API calls.
I struggled with gocloak GetUserInfo() method which always failed as part hub's auth middleware on missing or invalid token. Even wrote standalone GetUserInfo-like method in golang directly with net/http https://gist.github.com/aufi/57556376c440301713bde6b04b57ca4a it without gocloak and tested it with curl, however no sucess from the running hub.
Finally, the solution was already part of the existing auth token and its decode method which reads access scopes. So a new method getting the username was added to the auth provider and API Base was updated to call the Username method …

Track Username that created or updated models

---

hack/tool/tackle

Pathfinder path under the Hub API has changed, updating the tackle CLI
tool to use the hub prefix also for pathfinder.
https://issues.redhat.com/browse/TACKLE-649

Fix Pathfinder API path

---

api/tagtype.go

https://issues.redhat.com/browse/TACKLE-644

Tackle-644: Fixed returned created TagType.

---

hack/tool/README.md
hack/tool/tackle

Adding clean-all command to support scenario exporting Tackle 1.2 and importing later to some Tackle 2 instance which needs to be cleaned-up first and updating order of import objects which created empty tag types first and then tags with refs to the created tag types.
Also updated README with expected scenarios how the tool should be used.
https://issues.redhat.com/browse/TACKLE-660

Add full cleanup to tackle tool

---

api/task.go
hack/update/cancel.sh
model/task.go
task/manager.go

Add support for canceling tasks.
Adds: `/tasks/:id/cancel` endpoint which updates the Task.canceled attribute.
The task manager will:
- delete the associated pod.
- release the bucket.
- set the state=_Canceled_.
Related: With the addition of another update endpoint, it made sense to de-duplicate the omitted fields.
https://issues.redhat.com/browse/TACKLE-558

TACKLE-558: Task cancel.

---

hack/tool/README.md
hack/tool/tackle

Adding Python and PyYAML requirement into tackle tool README, updates making it working on Python3, but <= 3.9, few minor usage updates and skip Tackle2 token request when using --skip-destination-check option.
Now should work on Python 3.6 (RHEL8) out-of-the box and Python 3.9 (RHEL9) with manually installed PyYAML.

Update tool README with requirements

---

api/import.go

Updating Application CSV import dependency syntax to support only the full import format (without shorthands for dependencies), that removes counting back from the last dependency column.
Addressing technical debt issue: https://issues.redhat.com/browse/TACKLE-610

Update CSV import always count from zero

---

hack/tool/tackle

There was a problem with Tags - "Postgresql" in Tackle 1.2, "PostgreSQL" in Tackle 2.0. The pairing code which should migrate just Tags which are not already present in Tackle 2.0 consideted these to be a different tags. However sqlite prevented creation of the "Postgresql" tag when there was "PostgreSQL" alredy present in the same TagType.
Adding ```lower()``` method to Tag names to tackle tool to match tags case insensitive, so it considers "Postgresql" same as "PostgreSQL".
Export/import of whole Tackle 1.2 with -s option was not affected by this problem since all tags from 1.2 were exported and all seed tags from 2.0 are deleted before import.
Fixes: https://issues.redhat.com/browse/TACKLE-683

Update tool pair Tags case insensitive

---

api/application.go
api/pathfinder.go
api/pkg.go

Cascade application delete to pathfinder. Need to complete: https://issues.redhat.com/browse/TACKLE-673.
The UI will no longer need to explicitly delete of assessments when an application is deleted.
Requires: new pathfinder _bulkDelete_ endpoint.

Cascade application delete to pathfinder.

---

hack/tool/README.md
hack/tool/tackle

Adding --no-auth (-n shortcut) flag to Tackle CLI tool. If used, Keycloak token creation is skipped and empty token is used in Tackle API calls.
Needed for RHPDS setup.

Add --no-auth to Tackle tool

---

importer/manager.go

* Skip the tagtype and tag when the tag name is empty.
* Return an error if the tagtype is empty but tag name is present.
* Fix name normalization to only strip `-_\s`

Fix autocreation of tags

---

importer/manager.go

Trim leading/trailing spaces for application names (including dependency references).
https://issues.redhat.com/browse/TACKLE-739

TACKLE-739: App Import: trim leading/trailing spaces in app names.

---

importer/manager.go

Unknown and empty records in Application CSV importes were skipped in background import process (and counted as invalid) until now.
Adding error message to each such unknown record to match expectations from Tackle 1.2 usage.
Fixes: https://issues.redhat.com/browse/TACKLE-634
Fixes: https://issues.redhat.com/browse/TACKLE-742
Fixes: https://issues.redhat.com/browse/TACKLE-743

Always set error messages for invalid CSV records

---

importer/manager.go

2.1.0 backport of https://github.com/konveyor/tackle2-hub/pull/139
Unknown and empty records in Application CSV importes were skipped in
background import process (and counted as invalid).
Adding error message to each such unknown record to match
expectations from Tackle 1.2 usage.
Fixes: https://issues.redhat.com/browse/TACKLE-634
Fixes: https://issues.redhat.com/browse/TACKLE-742
Fixes: https://issues.redhat.com/browse/TACKLE-743

[Backport 2.1] Always set error messages for invalid CSV records

---

importer/manager.go

Adding error message for empty application name in CSV import matching to Tackle 1.2.
Fixes https://issues.redhat.com/browse/TACKLE-749

Validate non-empty Application Name in CSV Import

---

importer/manager.go

2.1.0 backport of https://github.com/konveyor/tackle2-hub/pull/142
Adding error message for empty application name in CSV import matching to Tackle 1.2.
Fixes https://issues.redhat.com/browse/TACKLE-749

[Backport 2.1] Validate non-empty Application Name in CSV Import

---

api/pkg.go
api/schema.go

Add /schema endpoint.
We needed to add an unauthenticated endpoint to support Hub (pod) readiness. May as well make it return something useful.
**Needed for Tackle 2.1.2.**

Add /schema endpoint.

---

database/db_test.go
database/pkg.go

As recommended by sqlite3 driver [documentation](https://pkg.go.dev/github.com/mattn/go-sqlite3#section-readme), we need to:
- Set the `_journal=WAL` in the DSN (better performance).
- Limit the open connections to (1).
The included unit test reproduced the _database locked_ error.  This patch eliminates the error.
https://issues.redhat.com/browse/TACKLE-654

TACKLE-654: Better support DB concurrency.

---

api/bucket.go

The buckets GET archive dir produces empty tar.gz archive if the directry was empty. It makes more sense to return 204 and no data in such case to tell client, that there is no data instead of sending 200 with empty tar.gz (that is ~100Bytes size).
Example:
```
$ curl -vOJ -H "X-Directory:archive" localhost:8080/applications/1/bucket/
*   Trying 127.0.0.1:8080...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /applications/1/bucket/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> X-Directory:archive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 …
```

Send 204 for empty buckets archive GET

---

Makefile
hack/cmd/addon/README.md
hack/cmd/addon/main.go

Fix hack addon tag management.
- Ensures type exists.
- Ensures tag exists.
Updates the README to running locally.
Add `run-addon` target to the makefile.

Fix hack addon tag management.

---

hack/cmd/addon/main.go

The logic needs to compare the IDs not the `Ref` object.

Fix tag conflict error in hack addon.

---

hack/cmd/addon/main.go

Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

fix: the closing tag was missing from the li element in html of the example addon code

---

api/application.go
api/task.go
api/taskgroup.go
auth/role.go
auth/roles.yaml

Fixes 403 error introduced with RWX solution when deleting the bucket. This solution adds specific scopes for the bucket resource and grants ALL which includes DELETE to addons for the application bucket.  It would be best not to give DELETE on applications to addons.
```
{"level":"info","ts":1674081007.5718358,"logger":"addon","msg":"|403|  DELETE /applications/2/bucket/windup/report"}
{"level":"error","ts":1674081007.5718448,"logger":"addon","msg":"Addon failed.","error":"Forbidden","stacktrace":"github.com/go-logr/zapr.
```

Add RBAC scope for bucket subresource.

---

addon/application.go
addon/tag.go
api/application.go
api/pkg.go
hack/cmd/addon/main.go

Currently the only way to mange the tag references on an application is to fetch the application; edit the tags (refs) and update the application. 
The goal here is to provide a more focused/intuitive way to do this with less chance for conflict when managing tags concurrently.
To easily:
- Resolve tag type names.
- Resolve tag names.
- Ensure tags and types exist.
- Explicit API to associate/disassociate tags with applications.
Adds APIs:
- GET /applications/1/tags - _List associated tags (refs)_.
- returns: []Ref
- POST /applications/1/tags - _Associate tag (by ref)_.
- body: Ref
- DELETE /applications/1/tags/45 - _Disassociate tag (by ID)_.
Adds addon (binding) API:
- Application.Tags() - _Returns sub-resource API_.
- List() - _List associated tags (refs)._
- Add() - _Add tag …

Add application/tags subresource.

---

api/addon.go
api/adoptionplan.go
api/application.go
api/base.go
api/businessservice.go
api/cache.go
api/dependency.go
api/group.go
api/identity.go
api/import.go
api/jobfunction.go
api/proxy.go
api/review.go
api/setting.go
api/stakeholder.go
api/tag.go
api/tagtype.go
api/task.go
api/taskgroup.go
go.mod

Consolidate the `*Failed` methods on the `BaseHandler` into a single method named `reportError` that preserves the same behavior.
* Gin binding errors are reported as `400 Bad Request`.
* RecordNotFound is reported as `404 Not Found` unless the HTTP method is `DELETE`. In that case it is reported as `204 No Content` (same as a successful delete).
* `fs.ErrNotExist` reported as `404 Not Found`.
* `DependencyCyclicError` is reported as `409 Conflict`.
* Unique and Primary Key constraint violations are reported as `409 Conflict`.
Signed-off-by: Sam Lucidi <slucidi@redhat.com>

refactor: consolidate API error reporting

---

.github/workflows/verifyPR.yml

This change makes it so that subsequent Pull Requests made to this project must follow the rules laid out in https://github.com/konveyor/release-tools/blob/main/VERSIONING.md
Signed-off-by: David Zager <david.j.zager@gmail.com>

:seedling: enforce style on PR titles

---

hack/tool/tackle

Fixing import action for tackle CLI from a dump originated in Tackle 1.2 which didn't have expected data-directory/buckets subdirectory. Workaround with --skip-buckets was possible but that's not that nice.
Signed-off-by: Marek Aufart <maufart@redhat.com>

:bug: Fix tackle import without buckets subdirectory

---

addon/adapter.go
addon/client.go
addon/file.go
api/bucket.go
api/file.go
api/import.go
api/pkg.go
auth/role.go
auth/roles.yaml
hack/add/file.sh
hack/cmd/addon/main.go
hack/update/file.sh
migration/v3/model/file.go
migration/v3/model/pkg.go
model/pkg.go
reaper/file.go
reaper/manager.go
reaper/ref.go
settings/hub.go

Support uploading and storing files independently of buckets.
Resource:
```
//
// File REST resource.
type File struct {
Resource
Name       string     `json:"name"`
Path       string     `json:"path"`
Expiration *time.Time `json:"expiration,omitempty"`
}
```
API:
- POST|PUT /files/_name_  - Create|update file. Returns `File`
- GET /files - List files. Returns `[]File`
- GET /files/:id - Get file content.  Accept=json returns `File`, else returns file stream.
- DELETE /files/:id - Delete a file.
Binding:
- File.Get(id uint, destination) - Get (downlaod) a file written to `destination`.
- File.Put(source) - Put (uploads) a file. Returns a `File`.
- File.Delete(id uint) - Delete a file.
Files with Zero reference count are reaped after 12 hours. **Q: Is this too long?**
---
Use case.  The …

:sparkles: Add file support.

---

.github/workflows/march-image-build-push.yml

Signed-off-by: Jason Montleon <jmontleo@redhat.com>
As a first step to automating releases I'd like to merge to each of the tackle repos a GitHub action to build multi-arch images for the main branch and tags. I've opened up a commit here for review and once we agree I will submit a PR to each of the tackle repos.
For a preview of what this looks like on quay see: https://quay.io/repository/jmontleon/tackle2-hub?tab=tags
Once those are up and they're approved we can turn off the quay auto builds, ensure the robot env vars are in the org, and the account is privileged to push to each repo.
Future improvements from here will include using manifest SHAs in the tag version CSVs and automating the release, ensuring we push a no arch bundle in our quay org, an updated index in our quay org, and …

:sparkles: Push multi-arch builds to quay

---

addon/client.go
api/application.go
api/bucket.go
api/pkg.go
api/task.go
api/taskgroup.go

Update the bucket APIs to return tarball for directories based on `Accept` header instead of `X-Directory` header. This will be simpler for browsers and file download widgets.
When the path is a directory in the bucket a tarball will be returned unless the client explicitly accepts `text/html`.
This should not require any changes in API clients (Like the CLI).

:sparkles: Bucket GET on directory using accept header.

---

.github/workflows/test-addons.yml
Makefile

Add the start-minikube and install-tackle targets to Makefile. Additionally, update the addons workflow to populate the HOST.
Signed-off-by: David Zager <david.j.zager@gmail.com>

:seedling: make start-minikube + install-tackle

---

addon/application.go
api/application.go
auth/role.go
auth/roles.yaml
hack/add/application.sh
hack/add/fact.sh
hack/cmd/addon/main.go
hack/delete/fact.sh
hack/update/application.sh
hack/update/fact.sh
migration/migrate_test.go
migration/v2/migrate.go
migration/v3/migrate.go
migration/v3/model/application.go
migration/v3/model/fact.go
migration/v3/model/pkg.go
model/pkg.go

Support more granular and atomic API for managing application _facts_.
Added:
- GET /applications/facts
- GET /applications/facts/_key_.
- POST /applications/facts/_key_.
- PUT /applications/facts/_key_.  (created as needed)
- DELETE  /applications/facts/_key_.
Go binding.
- Applications.Facts()
- List()
- Get()
- Set()  (created as needed)
- Delete()
For backwards compat and convenience, The Application.Facts will continue to be supported but we should recommend as _Best Practice_ for API users to use the sub-mainly to avoid conflict.
**Note** There is a bug in the ORM where JSON fields with _number_ roots is not scanned (unmarshalled) correctly.  When fact were embedded in Application this was not an issue.  Moving each fact to a new model/table, each fact value is now the root.  Fact …

:sparkles: Add application/facts sub-resource.

---

reaper/file.go
reaper/ref.go
settings/hub.go

Needed to use IsExported() instead of CanSet().
Other minor:
- passing model as pointer for efficiency.
- add/update logging.
- comments.

:ghost: Fix file reaping of rulebundle images and ruleset files.

---

addon/adapter.go
addon/client.go
api/auth.go

After changes:
```
[galt@desktop ~]$ curl  http://$(minikube ip)/hub/auth/login -X POST -H "Content-Type: application/json" -d "@login.json" | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3361    0  3321  100    40  43893    528 --:--:-- --:--:-- --:--:-- 44813
{
"user": "admin",
"token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItTWxjMU9wSUNXUjUxMUh..."
}
```
Also includes helpers for using the addon client

:sparkles: Update login endpoint to return token in JSON

---

api/application.go
api/bucket.go
api/task.go
api/taskgroup.go

Add bucket directory download content filtering. Support optional `?filter=<glob>` query parameter.
Example:  /applications/1/buckets/windup/report?*.csv the tarball will only contain .csv files.
Removed the optimization of returning NoContent when the tarball is empty.  I think this complicates what the client needs to do for no real gain. 
closes #243

:sparkles: Add bucket directory download content filtering.

---

api/application.go
hack/update/application.sh
migration/v3/model/application.go
migration/v3/model/applicationtag.go
migration/v3/model/tag.go

*Fixes a null pointer while generating the list of tag refs for the resource to be returned from an Application create.
*Fixes a null constraint violation caused by GORM not omitting associations properly while updating.

:ghost: fix null issues relating to tag associations

---

.github/workflows/march-image-build-push.yml

Multiple rapid merges can result in more than one build being triggered and there is no guarantee which will finish first. Yesterday we saw two image builds complete at nearly the same time with UI leading to uncertainty as to whether the latest image reflected the latest merge.

:bug: Limit Multi-Arch Build Concurrency

---

api/application.go
api/base.go
api/task.go
api/taskgroup.go

Only the last call to `Omit` is honored when building a query, so change all multiple uses to a single use with multiple parameters.
Also, exclude more fields from `BaseHandler.fields`, which is used when determining which fields to updaate:
* Pointers to struct
* Arrays and slices
* Pointers to arrays and slices

:bug: Fix issues with updating models that have associations

---

api/base.go

Fix BaseHandler.fields() not including json fields []byte.
Fixes PUT on:
- tasks, taskgroups
- applications (facts & repository)
- applications/facts
- settings
Fixes docker build.  The reflect.Ptr was renamed to reflect.Pointer in 1.18. The dockerfile includes [go-toolset:latest](https://catalog.redhat.com/software/containers/ubi9/go-toolset/5ce8713aac3db925c03774d1?container-tabs=overview) which includes 1.18.9. The patch to use (deprecated) reflect.Ptr should not be necessary.  But, the docker build fails without it.
```
api/base.go:143:9: undefined: reflect.Pointer
make: *** [Makefile:30: vet] Error 2
```
Regression introduced in pull/255 [here](https://github.com/konveyor/tackle2-hub/pull/255/files#diff-b3ac3832e61047a1ffffe16d97019d06999f7c9653bc29f35212efbe18f88210R155).

:bug: Fix PUT settings not updating the value.

---

.github/workflows/main.yml

The purpose of this action is to test builds before merge. Multi-Arch builds take a long time, so we do a quicker amd64 build to catch pretty much anything but extreme corner cases and emulation bugs.
The multi-arch build runs to build and push images after merge so running this is unnecessary and probably confusing.

:ghost: Disable redundant post merge build

---

api/task.go

Don't use `TaskHandler.omitted()` when creating a Task through the API. Doing so was causing the `BucketID` that was being set by the `BeforeCreate` hook to not be persisted on the new Task row in the database. (The in-memory ID for the orphaned bucket was being returned in the response to the `POST`, but subsequent `GET`s would not not include it and the bucket would be reaped.)
`omitted()` is to ensure that fields that are not allowed to be updated through the API (and are thus not propagated from the resource to the model) are not zeroed out when the task is updated.

:bug: Don't omit BucketID when creating tasks

---

addon/application.go

Ensure that Replace() associates a unique set of tag ids.  Rather than making this the responsibility of the caller, it seems more helpful to de-duplicate here.  Also, this consistent with _Ensure__() methods.
Fixes: https://issues.redhat.com/browse/MTA-279

:bug: Ensures Replace() associated tag ids are unique.

---

api/watchdog.go
cmd/main.go

Add `watchdog` handler.
Performs chain _health_ validations.  Detect invalid position of the Transaction (when present in the chain).

:ghost: Add watchdog handler.

---

auth/reconcile.go

Instead of trying to log in to Keycloak every second for three minutes before giving up and allowing reconcile to fail, retry every three seconds forever until logging into keycloak succeeds.

:ghost: Attempt to reconcile keycloak indefinitely

---

api/auth.go
auth/auth_test.go
auth/builtin.go
auth/keycloak.go
auth/provider.go
auth/request.go
task/auth.go
task/manager.go

The auth.Request enhanced to include a `*gom.DB` to ensure the `auth` package uses the DB (or Tx) passed in the gin context instead of the global (main) DB client.  This protects against deadlock caused when the global (main) DB client is used after a transaction has started.

:ghost: auth.Validator must use DB passed in the gin context.

---

addon/adapter.go
addon/client.go

PROBLEM:
The addon (binding) is designed to detect and deal with temporary hub unavailability. The primary use case is a hub pod restart. It is intended to retry requests for 10 min.  In reality, this ends up being 20 min (2 x 10).  This is because in the adapter Run(), a caught error/panic is reported to the hub which results in entering the retry logic a 2nd time.
SOLUTION:
Maintain the error state on the client so subsequent requests will fail immediately.

:bug: Adjusted addon binding retry.

---

api/import.go

CreateUser field was empty for ImportSummaries, it turned out that there is missing Auth middleware for Import-related API endpoints.
Adding the Required("imports") middleware to the Imports endpoint.
API returns non-empty user field now:
```
$ curl -F "file=@import.csv" http://localhost:8080/importsummaries/upload
{"id":16,"createUser":"admin.noauth","updateUser":"","createTime":"2023-04-04T18:46:45.588499423+02:00","filename":"","importStatus":"Completed","importTime":"2023-04-04T18:46:45.588499423+02:00","validCount":0,"invalidCount":0,"createEntities":true}
```
Fixes: https://issues.redhat.com/browse/MTA-129

:bug: Add Auth Require to Import API

---

api/import.go

6.1 backport of https://github.com/konveyor/tackle2-hub/pull/283
CreateUser field was empty for ImportSummaries, it turned out that there is missing Auth middleware for Import-related API endpoints.
Adding the Required("imports") middleware to the Imports endpoint.
API returns non-empty user field now:
```
$ curl -F "file=@import.csv" http://localhost:8080/importsummaries/upload
{"id":16,"createUser":"admin.noauth","updateUser":"","createTime":"2023-04-04T18:46:45.588499423+02:00","filename":"","importStatus":"Completed","importTime":"2023-04-04T18:46:45.588499423+02:00","validCount":0,"invalidCount":0,"createEntities":true}
```
Fixes: https://issues.redhat.com/browse/MTA-129
---------

:bug: [BACKPORT] Add Auth Require to Import API (#283)

---

auth/reconcile.go

Instead of trying to log in to Keycloak every second for three minutes before giving up and allowing reconcile to fail, retry every three seconds forever until logging into keycloak succeeds.

:ghost: [Backport] Attempt to reconcile keycloak indefinitely (#278)

---

api/import.go

Fix for 6.1 Auth Require in Imports. Not needed in main, needed in 6.1 only.
Tested locally and runs on mta-6.1 now.
Related to: https://github.com/konveyor/tackle2-hub/pull/286 and https://github.com/konveyor/tackle2-hub/pull/283

:bug: [6.1 only] Fix Auth Required import

---

api/api_test.go
api/base.go

Fixes a regression introduced when Accepted() was _enhanced_ to support wildcards.
When used to determine of bucket and file endpoints are to return file content both curl and browsers passed */* which results in the endpoints returning html instead of streaming a file.

:bug: Fix accepted.

---

.github/workflows/main.yml
binding/identity.go
binding/proxy.go
binding/richclient.go

Adding identity and proxy methods to binding package. Enabling Hub API test execution on PRs ```Build Hub / test-api (pull_request)``` (in disconnected mode).
Follow-up on https://github.com/konveyor/tackle2-hub/pull/268

:seedling: Add identity, proxy bindings and enable API tests

---

tracker/jira/connector.go
tracker/manager.go

* report status based on status category rather than status name
* Make sure tracker error message is cleared when a connection is reestablished

:bug: Improve Jira issue status reporting

---

tracker/jira/connector.go

It's possible for the Jira client to return a nil response, so we need to check it before using it. Other locations are already safe because the `handleJiraError` function checks the response for nil.

:bug: Fix possible nil ptr dereference in Jira refresh

---

api/analysis.go
api/group.go
api/jobfunction.go
api/review.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

QE reported failures on Get actions for jobfunction, group. Updating swagger annotation to expect single value instead of array (jobfunction and review) and make a small fix when Get returned model instead of api package struct (group).
Also adding Analysis endpoint methods to generated swagger spec.
Fixes: https://issues.redhat.com/browse/MTA-582

:bug: Update Swagger fix array/single, add analysis

---

settings/addon.go
task/manager.go

There are is no meaningful advantage to mounting the emptyDir over the addon using the containerfs.
Mounting the emptyDir and setting (forcing) the workingDir is opinionated in ways that overrides the container configuration.
Backwards compatible with _known_ addons.

:sparkles: Emptydir and setting the workingDir discontinued.

---

Makefile
test/api/identity/api_test.go
test/api/identity/pkg.go
test/api/identity/samples.go
test/api/proxy/api_test.go
test/api/proxy/pkg.go
test/api/proxy/samples.go

Adding Indetity and Proxy resources to API tests. Identity provides samples with login/password, key and settings file.
Related to https://github.com/konveyor/tackle2-hub/pull/268

:seedling: Add Identity and Proxy to API tests.

---

api/pathfinder.go
cmd/main.go
metrics/manager.go
metrics/pkg.go
settings/all.go
settings/metrics.go
task/manager.go
tracker/manager.go

By default, metrics are enabled and are available at `:2112/metrics`. To change the port, set the `METRICS_PORT` environment variable. To disable metrics, set `METRICS_ENABLED` to false.
* Current number of applications in inventory
* Count of tasks initiated
* Count of assessments initiated
* Count of issues exported to jira
Implements https://github.com/konveyor/tackle2-hub/issues/305

:sparkles: Expose Prometheus metrics

---

README.md

Adding on-merge Hub build workflow and nightly tests badges to README (both are green as of now).

:ghost: Add test badges to README

---

Makefile
api/analysis.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
migration/v4/model/analysis.go

Add analysis total effort and include in the IssueReport.
Also, noticed the IssueReport is not marshalled with `Issue` inline in YAML.  This is because the yaml:,inline tag is missing. However, the report redefines the incidents field.  This (field override) works with the json decoder but not the yaml decoder.

:sparkles: Add analysis total effort and include in the IssueReport.

---

addon/application.go
addon/client.go
api/analysis.go
api/base.go
docs/binding.txt
docs/docs.go
docs/swagger.json
docs/swagger.yaml
hack/add/analysis.sh
hack/cmd/addon/main.go

The approach of: using `File` and `AnalysisManifest` is intended to be more RESTful but after test driving it seems overly complicated.  Seems more straight forward to use a multi-part for as the _Manifest_.
Adds addon binding Client.FileSend() used by the `File` and `Application.Analysis` APIs.

:ghost: Using multi-part form instead of manifest.

---

addon/application.go
api/application.go
hack/update/fact.sh

Fix the addon binding: Body is Fact (not the value).
Fix Both GORM create and save will add ON CONFLICT clause when the PK is set.  When source="", the entire composite PK is not considered set.
Backport: 0.2

:bug: Addon fact put

---

addon/application.go
api/application.go
hack/update/fact.sh

Fix the addon binding: Body is Fact (not the value).
Fix Both GORM create and save will add ON CONFLICT clause when the PK is set.  When source="", the entire composite PK is not considered set.

:bug: [backport] Addon fact put

---

api/base.go
api/tag.go

There is a Ref API struct used e.g. in Tag-TagCategory association. API e.g. on Tag create doesn't load the Category so the API reponse doesn't contain Category Name.
Trying to solve this **either** with pre-loading the Category on TagCreate or drop name field from the Ref API response. **To be discussed**, looking forward to comments in this PR.
Related to https://issues.redhat.com/browse/MTA-674

:sparkles: Omit Ref empty Name in API

---

api/pathfinder.go

The UI makes POST requests to /pathfinder/assessments/assessment-risk in order to show the calculated risk on the side bar. This needs to be excluded in order to be sure we're only counting initiated assessments.
Check that POST requests are to /pathfinder/assessments.
Fixes https://issues.redhat.com/browse/MTA-682

Fix Pathfinder assessment counting

---

api/analysis.go
api/filter/filter.go
api/filter/filter_test.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
migration/migrate.go

closes #367 
Also refit RuleReport using the _view_ pattern `select * from (select ...)`.
The _view_ pattern supports filtering and sorting on all report fields including derived (virtual) columns such as count().

:ghost: IssueReport refactored into: AppReport.

---

api/pathfinder.go

The UI makes POST requests to /pathfinder/assessments/assessment-risk in order to show the calculated risk on the side bar. This needs to be excluded in order to be sure we're only counting initiated assessments.
Check that POST requests are to /pathfinder/assessments.
Fixes https://issues.redhat.com/browse/MTA-682

[Backport] Fix Pathfinder assessment counting

---

api/dependency.go
binding/dependency.go
binding/richclient.go
test/api/dependency/api_test.go
test/api/dependency/pkg.go
test/api/dependency/samples.go

Upstream issue [https://github.com/konveyor/tackle2-operator/issues/220](https://github.com/konveyor/tackle2-operator/issues/220)
Issue in the repo #370 
added api_test.go,pkg.go,samples.go in `dependency` directory. Also added `dependency.go` in binding package and added dependency client in `binding/richclient.go`

:seedling: add dependency  package in test/api

---

api/analysis.go
api/application.go
api/base.go
api/bucket.go
api/businessservice.go
api/dependency.go
api/error.go
api/file.go
api/group.go
api/identity.go
api/jobfunction.go
api/migrationwave.go
api/proxy.go
api/reflect/fields.go
api/review.go
api/ruleset.go
api/setting.go
api/sort/error.go
api/sort/sort.go
api/stakeholder.go
api/tag.go
api/tagcategory.go
api/task.go
api/taskgroup.go
api/ticket.go
api/tracker.go

The approach is to build the Sort object using the fields in the model used for the query.
Revert the usage of h.Paginated() in all but analysis.go. We can add pagination and sorting more deliberately as needed. This is most of the diff.
Moved the sorting object to the _new_ sort package.
Moved the BaseHandler.fields() and BaseHandler.nameOf() to a _new_ reflect package.  The Fields() used for both update and inspection of models for sort fields. 
Add Sort.With() enhanced to provide validation.

:sparkles: Add sort field validation.

---

tracker/jira/connector.go
tracker/pkg.go

Backport #374 
Fixes https://issues.redhat.com/browse/MTA-699 by making it possible to authenticate with On-Prem Jira deployments that use bearer token auth.

[backport] :sparkles: Support JIRA Bearer Auth (#374)

---

importer/manager.go

release-0.2 backport of Update new TagCategory in CSV import https://github.com/konveyor/tackle2-hub/pull/384
Application CSV import can create new Tag Categories. For performance reasons, list of Tag Categories is loaded from database before processing all Tag imports. This list wasn't updated with newly created Tag Categories, so it was not possible create a new Tag Category and assign multiple Tags to it on the Same application.
Adding new created Tag categories to the cached Tag Categories list.
Fixes: https://issues.redhat.com/browse/MTA-480

[backport] :bug: Update new TagCategory in CSV import

---

migration/v2/model/identity.go
migration/v4/migrate.go
migration/v4/model/identity.go
migration/v4/model/pkg.go
test/api/identity/api_test.go

release-0.2 backport of Add uniq Name constrain to Identity #377
Adding uniq Name constraint to Identity model. The constraint is enforced regardless Identity Kind in similar way as UI do for a while.
Fixes: https://issues.redhat.com/browse/MTA-27

[backport] :bug: Add uniq Name constrain to Identity

---

api/analysis.go
api/filter/filter.go
api/filter/filter_test.go

Support LIKE filter with _LIST_ (OR) values in the _filter_ package.
```
?filter=category~(This*|That*)
(category LIKE 'This%' OR category LIKE 'That%')
```
Add support for filter on Labels AND using LIKE.  This needs to be done with an INTERSECT so cannot be entirely provided by the _filter_.
```
?filter=labels~(This*,That*)
SELECT ID FROM Thing WHERE category LIKE 'This%' 
INTERSECT 
SELECT ID FROM Thing WHERE category LIKE 'That%'
```
Adds Field.Expand() greatly simplifies building the query for AND Lists by delegating the building of each _WHERE clause_ to the _filter_ package. Applied pattern everywhere.
Fixes RuleReport filter on labels.

:bug: Support LIKE filter on lists.

---

tracker/jira.go
tracker/manager.go

Fixes https://issues.redhat.com/browse/MTA-809 by moving the counter increment into the specific connector's create implementation, after the ticket has been created successfully.

:bug: metrics: count issue export only when successful

---

migration/v5/model/application.go
migration/v5/model/tracker.go

Cascade delete Tickets when their Application is deleted. Don't allow a Tracker to be removed when it has tickets.
Fixes https://issues.redhat.com/browse/MTA-811

:bug: Fix ticket/tracker cascade deletes

---

hack/add/analysis.sh

For parsing in the UI, we're assuming there are exactly 2 spaces between the line numbers and the code, and that the line numbers are right-aligned before these 2 spaces (possible leading whitespace). To test the corner cases of the parser, this fixes the indentation in the mock codeSnip and changes the line numbers so the snip contains the boundary between line 99 and line 100 (leading whitespace change).

:ghost: Hack: consistent indentation in codeSnip

---

api/analysis.go

The _inner_ query for labels was overwriting `q` which could have contained Issue fields where clauses.
Updated other queries to use `iq` (_inner query_) convention for consistency.

:bug: Fix labelIDs() query ignoring other issue fields when labels included.

---

api/analysis.go
api/base.go
database/pkg.go

To support pagination, the hub sets the X-Total header to tell the caller (The UI really) the total number available to be displayed as the total number of pages.  To accomplish this, the hub executes the query 2 times.  First to get the count(*), again to fetch the data.  This doubles the latency and overhead in the hub for each request.  Unfortunately, the sq.Rows does not provide the count.
Better performance iterating the _cursor_ (sql.Rows) instead of running the query twice. This also eliminates the race condition between the count (query) and fetch query.
Adds a new _cursor_ object used to consistently:
- execute the query
- iterate the sql.Rows
- scan
- paginate
- count
The count is capped at 50,000 because for tables (like incident) the total can be tens-hundreds of millions. …

:sparkles: Better perf using the cursor.

---

api/analysis.go
migration/v5/model/analysis.go

Add `IssueReport` needed for single-application flow.  Making this a separate report because joining with the (very large) Incident table is very expensive if not qualified by application.
Updated the RuleReport, since the query got updated to group by RuleSet, Rule, correlating using the map isn't necessary.

:sparkles: Add new IssueReport.

---

hack/next-migration.sh

Fix generated model/pkg.go `All()`:
- models need to be in order of dependency (not alphabetical).
- includes unwanted models.
The fix is to build the new All() using the previous migration All().

:seedling: Fix generated model pkg.go.

---

api/analysis.go

Add IssueAppReport.Description.
Add IssueReport.Issue.ID

:sparkles: additional report fields.

---

addon/task.go
api/task.go
hack/add/analysis.sh
hack/cmd/addon/main.go
migration/v6/migrate.go
migration/v6/model/pkg.go
migration/v6/model/task.go
migration/v6/model/taskgroup.go
task/manager.go

Task.Error and TaskReport.Error renamed:
Task.Errors []TaskError
TaskReport.Errors []TaskError
closes #411

:sparkles: Structured task errors.

---

api/analysis.go
hack/add/analysis.sh

Adds `Links` to both: /rules and /applications/:id/issues reports.
hack script adds markdown issue description and links.

:sparkles: Add links to rules and issues reports.

---

api/analysis.go

Missed this endpoint during one of the sort/pagination refactors.
Just needs to be _wired up_ properly.

:bug: Fix DepReport sort.

---

api/analysis.go
hack/add/analysis.sh

When labels filter specified, the inner query was overwriting the outer (main) query.
Few other fixes.
Adds labels to resource returned by /report/dependencies/applications.
Adds sample label to one of the deps in hack.

:bug: Fix dep report filter depIDs(); add lables to dep apps report.

---

task/manager.go

Fixes https://issues.redhat.com/browse/MTA-894
Backport of #438

[release-0.2] :bug: metrics: only count the first time a task starts

---

tracker/jira.go

New issues that belong to issue types with the `subtask` flag set (including the "Sub-task" built in issue type) are required to have a parent issue set. We don't support setting the parent issue, so exporting migration waves as issues of such types will fail. To fix this, avoid returning issue types with the `subtask` flag set from the `/trackers/:id/projects/:pid/issuetypes` endpoint.
Fixes https://issues.redhat.com/browse/MTA-870 by removing the option to export as a Sub-task.

:bug: Don't return issueTypes with the subtask flag set

---

binding/client.go
binding/error.go

Add RestError for generic REST errors.
Produces errors with descriptions like:
```
GET /hub/applications/34 failed: 404(Not Found) body: {"error":"record not found"}
```

:bug: Better reporting of REST errors.

---

tracker/jira.go

The Epic issue type has an additional required field for Server/Datacenter instances. We don't currently have a solution in place for dealing with additional required fields, so hide that issue type on on-prem instances for now.
Fixes https://issues.redhat.com/browse/MTA-873

:bug: Hide Epic issue type for On Prem trackers

---

api/task.go

Flatten the task and report.
Report.Errors are prepended to the Task.Errors.
Report.Activity copied to Tack.Activity.  We may want to add Task.Activity later and report manager activity but this is good enough for this iteration.
Override the Task.State (succeeded) when the report has Failed.
---
```
id: 5
createtime: 2023-07-24T19:10:33.438493425Z
name: Daytrader7.1.windup
addon: analyzer
data:
mode:
artifact: ""
binary: false
diva: false
withDeps: true
rules:
labels:
excluded: []
included:
- konveyor.io/target=cloud-readiness
- konveyor.io/target=azure-aks
- konveyor.io/target=azure-container-apps
- konveyor.io/target=azure-appservice
- konveyor.io/target=azure-spring-apps
- konveyor.io/target=camel3
- konveyor.io/target=java-ee7
- konveyor.io/target=resteasy3
- konveyor.io/target=eap
- …
```

:sparkles: Flattened task/report.

---

addon/adapter.go
addon/task.go
hack/cmd/addon/main.go

Add _raw_ methods used by addons to report both errors and activity. The reason is to reduce the number of API calls when reporting large numbers.
For example, the _addon.command_ package reports stdout/stderr for failed commands which can be hundreds (or thousands of lines).  Calling Activity() hundreds of times result in hundreds of API calls.
Another example is the reported analyzer errors.
Another aspect is to formalize multi-line activity.  This PR codifies the convention of:
```
- This is a list of:
- > One
- > Two
- > Three
```
and, simplifies the API.
The tackle2-addon _command_ package will need to be updated once this merges to use RawActivity() for stdout/stderr. reporting.
The tackle2-addon-analyzer will need to updated to use both methods in select places as well.

:sparkles: Add raw methods for error and activity reporting by addons.

---

cmd/main.go
migration/v7/migrate.go
migration/v7/model/jobfunction.go
migration/v7/model/ruleset.go
migration/v7/model/tag.go
migration/v7/model/tagcategory.go
seed/jobfunction.go
seed/pkg.go
seed/ruleset.go
seed/seed.go
seed/tag.go

Fixes an issue where new objects were being created with a UUID of the empty string instead of a null, which was interfering with the uniqueness test.

Make UUID field a pointer

---

tracker/manager.go

Creating the tracker connector inside of the loop results in Decrypt being called on the tracker's Identity once for each ticket to be created. Decrypt is not idempotent, so this scrambles the password on subsequent calls. This was causing batch creation of Jira tickets to fail strangely, as only the first ticket in any batch would be created before the credentials were scrambled.
Fixes https://issues.redhat.com/projects/MTA/issues/MTA-696

:bug: Only create connector once to fix ident mangling

---

addon/task.go
hack/cmd/addon/main.go

This PR simplifies the API for use cases for which the _new_ RawError() and RawActivity() were meant to support.  
Especially the RawActivity().  The main case here is to report multi-line activity. In this case the activity is reporting something followed by multiple lines.  The first line is the-activity followed by multiple-lines of detail.  This PR simplifies this more than the RawActivity() because it can be achieved in (1) addon.Activity() call.
For example:
```
addon.Activity("Doing something with a list of things:\n%s", "One\nTwo\nThree")
```
Results  in:
```
- Doing something with a list of things:
- > One
- > Two
- > Three
```
The Error and RawError is achieved by reversing which is the edge case.  Errorf() is added (instead of RawError) which makes for a more intuitive API.

:sparkles: RawError, RawActivity simplified.

---

test/api/ruleset/api_test.go

API tests failed on Ruleset empty seed check. Removing Ruleset seed check for now (until we have tackle2-seed related test requirements).
```
=== RUN   TestRuleSetListSeed
time=2023-07-25T09:37:02+02:00 level=info msg=[binding] |200|  GET /rulesets
api_test.go:83: Seed looks empty, but it shouldn't.
--- FAIL: TestRuleSetListSeed (0.00s)
```
Related to https://github.com/konveyor/tackle2-hub/pull/450 and https://github.com/konveyor/tackle2-seed

:ghost: Remove Ruleset seed test

---

addon/adapter.go
addon/error.go
binding/application.go
binding/client.go
binding/error.go
hack/cmd/addon/main.go
task/manager.go

The SoftError was originally intended to support addons returning an error that would not be stack traced and not trigger a task (pod) retry.  However, in practice:
- almost all errors should not be retried.
- SoftError has not been consistently adopted.
As a result, SoftError has been all but removed and **deprecated**.  Leaving it in the addon binding for backwards compat.
Further, the adapter Run() will no longer trace caught errors because there cannot be any expectation that addon writers will _wrap_ errors and logging errors in Run() is useless.  The addon returning an error will always result in exit(1) - 
_application failed_.  The task manager will retry for: code=137 (SIGKILL) Only.
Fixed binding Client.restError() for issue found while testing.

:ghost: SoftError deprecated.

---

test/api/ruleset/samples.go

Image is not part of Ruleset anymore, removing from sample Rulesets.
Related to https://github.com/konveyor/tackle2-hub/pull/464

:ghost: Fix Ruleset API test after refactoring

---

binding/review.go
binding/richclient.go
docs/test-api-matrix.md
test/api/review/api_test.go
test/api/review/pkg.go
test/api/review/samples.go

Add review API Test
Work to be Done
1. Check for Review.List()
2. Check for Copy Root

:seedling: add Review API Test

---

api/ruleset.go
migration/v8/migrate.go

Removes unwanted RuleSet columns that should have been removed in model version:8:
- Custom
- ImageID
The imageID causes problems for the File reaper.  The reaper no longer recognizes RuleSet as a file _owner_ and tries to delete the associated image `File`.  This fails due to the FK constraint.

:bug: Fix dangling ruleset ref to image File.

---

api/analysis.go
api/filter/filter.go
api/ruleset.go

The `Relation` validation was originally added to support:
```
tag=(A,B,C)
```
Where tag = A **and** B **and** C which is implemented as an SQL INTERSECT.
However, it seems the `Labels` use cases are implemented as JSON query.  This PR attempts to provide a more intuitive name.
Replaces:
```
{Field: "Labels", Kind: qf.STRING, Relation: true}, 
```
With
```
{Field: "Labels", Kind: qf.STRING, And: true}, 
```

:ghost: Relation renamed.

---

task/manager.go

Task retry strategy improved in much earlier PR but missed this scenario.  The improvement was to adjust the retry logic to be more narrowly focus on only scenarios worth retrying.
Fixed.

:bug: Fix task failed when not killed.

---

api/analysis.go
auth/role.go
auth/roles.yaml

Fix RBAC for:
- /analyses - _This is the primary endpoint for analyses_
- /applications/:id/analyses endpoints - _This is the analyses subresource under applications_.
Roles:
- Addon: CRUD for:
- /applications/:id/analyses
- Admin, Architect: CRUD for:
- /analyses
- /applications/:id/analyses
- Migrator, Project-Manager: Read-Only, 
- /analyses
- /applications/:id/analyses

:bug: Fix analyses RBAC.

---

api/ruleset.go
binding/migrationwave.go
binding/richclient.go
docs/test-api-matrix.md
test/api/migrationwave/api_test.go
test/api/migrationwave/pkg.go
test/api/migrationwave/samples.go

Added the migration wave API test

:seedling: add migrationwave API test

---

.github/workflows/main.yml

This will import the global CI workflow, which runs the end to end tests defined in https://github.com/konveyor/go-konveyor-tests (for now, it will be expanded to more suites as they become quick and stable enough). This helps to ensure that individual components aren't breaking the project as a whole, which should help to smooth out the release process.

:sparkles: import global ci workflow

---

hack/tool/tackle

Login endpoint provided by older Keycloak versions used by CLI tool is not available in current Konveyor version (>=0.2).
Replacing Keycloak get auth token action with Hub's /auth/login endpoint.
Tackle1 export login keeps the original Keycloak login.

:seedling: Update CLI tool login via Hub

---

seed/pkg.go

The seed versioning capability is not necessary and complicates keeping the seed and hub repos in sync. If this is needed in the future, the design should be reevaluated.

:warning: Disable seed versioning

---

go.mod
go.sum
seed/jobfunction.go
seed/questionnaire.go
seed/ruleset.go
seed/seed.go
seed/tag.go
seed/target.go

Adds logic to seed Questionnaires. Fixes a bug that would have caused an unnecessary query when an item to be seeded is found by UUID and not being renamed.

:sparkles: Apply Questionnaire seeds

---

binding/questionnaire.go
binding/richclient.go
docs/test-api-matrix.md
test/api/questionnaire/api_test.go
test/api/questionnaire/pkg.go
test/api/questionnaire/samples.go

Adding Questionnaire endpoint to binding and basic API test.
Started looking on Pathfinder export/Assessment import (via CLI), adding basic API test as a side-effect.
Related to https://github.com/konveyor/tackle2-hub/pull/492

:seedling: Add Questionnaire to binding and API test

---

api/application.go
api/archetype.go

If the "sections" field of the assessment resource is populated when POSTing an assessment, then the
sections will not be overridden by values from the questionnaire and the assessment will not be autofilled.

:sparkles: Allow creating assessments "as-is"

---

api/analysis.go

The `/applications/:id/analysis` and `/applications/:id/analysis/report` returned the report for: analysis.ID=:id (application ID) instead of the Last analysis for the application.ID = :id.
Potentially related to: https://issues.redhat.com/browse/MTA-1344

:bug: Fix latest analayis report.

---

Dockerfile

Better support for test run analysis with seed PRs using 
`--build-arg SEED_PROJECT <url>`
`--build-arg SEED_BRANCH <branch> `
Example:
```
$ docker build . -t quay.io/jortel/tackle2-hub:latest \
--build-arg 'SEED_PROJECT=jortel/tackle2-seed' \
--build-arg 'SEED_BRANCH=add-targets' \
&& docker push quay.io/jortel/tackle2-hub:latest
```

:ghost: Support seed build args.

---

api/application.go
api/archetype.go
api/assessment.go

Marshalling the Assessment resource's `Sections` field unconditionally results in populating the model's `Sections` with the byte string `null`, which breaks the test for empty sections, making it always look like the assessment is being imported with sections "as-is". To fix this, only marshal the sections in the Assessment's `Model()` method if they are not empty. Additionally, replace the `if m.Sections == nil` test with a test for length, which works on nil as well as empty slices.

:bug: Only marshal assessment sections if not empty

---

api/questionnaire.go
migration/v10/model/assessment.go

Only changing the `required` field is permitted for builtin questionnaires, all other changes and deletion are disallowed.

:bug: Protect builtin questionnaires from update/delete

---

api/analysis.go
api/bucket.go
tar/filter.go

The HTML report (tarball) is composed/streamed by the hub in steps:
1. Add the static report directory (template).
2. Add the composed `output.js` file which contains the analysis data.
Using this method, the ReportWriter was adding the `output.js` (entry) twice in the tar.  First from the static report (template) and the second generated by the hub.
The tar command line seems to deal with this by overwriting the file. However the _extract_ functionality used by browsers ignores the 2nd occurrence.
The fix is to filter out the 1st output.js when using tar.Writer.AddDir().  
The `Filter` in the `tar` package only supported _include_ filtering.  This PR updates the `tar.Filter` to support both _included_ and _excluded_ patterns.
Refitted and tested the /bucket.

:bug: Fix HTML analysis report.

---

assessment/section.go

This was missing from the Assessment/Questionnaire sections and is necessary to completely implement the enhancement.

:sparkles: Add `comment` string field to Section

---

api/analysis.go

The static report JS needs the app ID to be a string.

:bug: Static report app id needs to be a string.

---

test/api/identity/samples.go

Updating Maven Identity sample to use (currently) correct "maven" kind instead of "mvn" to make it working with addon https://github.com/konveyor/tackle2-addon-analyzer/blob/61027b29f36ffa5b884ceac81c61d74341bdd762/cmd/mode.go#L151-L153

:seedling: Fix Identity API test Maven sample

---

binding/richclient.go
binding/ticket.go
docs/test-api-matrix.md
test/api/ticket/api_test.go
test/api/ticket/pkg.go
test/api/ticket/samples.go

:seedling: add ticket API test

---

settings/hub.go
task/manager.go

Using the container status `Reason` for more accurate reporting.
```
state: Failed
image: quay.io/jortel/tackle2-addon-analyzer:debug
pod: konveyor-tackle/task-13-gcmjs
retries: 1
started: 2023-10-16T10:36:30.221282042-07:00
terminated: 2023-10-16T10:36:40.301254088-07:00
bucket:
id: 17
name: ""
errors:
- severity: Error
description: 'Pod failed: OOMKilled'
```
Also, the RWX should be disabled by default.

:sparkles: Better pod OOM reporting.

---

api/bucket.go
test/api/bucket/sample/sample2.txt
test/api/task/bucket_test.go

The refactor to using the new `tar` package accidentally removed setting the X-Directory:Expand.
As a result, the client is not expanding downloaded directory (tarball).
---
Fixed API tests.  The bucket directory test really needs 2+ files to be accurate. It missed this issue.
Added the task bucket (subresource) test for symmetry.

:bug: Bucket getdir

---

test/api/tracker/api_test.go

Fixing resources cleanup at the end of the test, by sending the identity's ID to `Identity.Delete`  instead of the tracker's ID

:seedling: Delete identity associated with tracker

---

api/adoptionplan.go
api/analysis.go
api/assessment.go
api/base.go
api/group.go
api/import.go
api/migrationwave.go
api/review.go
api/ruleset.go
api/stakeholder.go
api/target.go
api/ticket.go
api/tracker.go

:bug: Explicitly set yaml names for camelCased fields

---

auth/builtin.go
auth/provider.go
hack/jwt.sh
task/auth.go

Add hack script to generate jwt tokens for _builtin_ auth.  Likley used by actors such as the operator for migration related to upgrade.
Related:
- auth.Validator signature changed to return error.  This is more flexible and _failures_ can be propagated.
- auth.Builtin.Authenticate() returns NotAuthenticated when should have returned NotValid for clearity.
- auth.NotValid includes `Reason`.

:ghost: add hack to generate jwt token.

---

api/application.go
api/archetype.go
api/assessment.go
api/bucket.go
api/businessservice.go
api/dependency.go
api/group.go
api/identity.go
api/import.go
api/jobfunction.go
api/migrationwave.go
api/proxy.go
api/questionnaire.go
api/review.go
api/ruleset.go
api/stakeholder.go
api/tag.go
api/tagcategory.go
api/target.go
api/taskgroup.go
api/ticket.go
api/tracker.go

The yaml encoder/decoder needs to be explicitly told inline the `Resource` struct's fields on each of the API resources, otherwise attempts to bind requests that include Resource fields (`id`, `createTime`, `createUser`, `updateUser`) fail.

:bug: Add `yaml:"inline"` to Resource field tags

---

api/application.go
assessment/membership.go

The assessment stakeholder relationships need to be preloaded so that the `applications/id/assessments` and `archetypes/id/assessments` subresources populate their association fields properly.

:bug: Preload assessment stakeholder relationships

---

api/base.go
api/task.go
api/taskgroup.go

Fix JSON encoding of resources fields of type _any_.
When the `content-type` is YAML, the decoded resource fields of type _any_ will be unmarshalled as `map[any]any`.  This is legal for YAML but not JSON.  As a result, the JSON encoding fails and the field value is NOT stored.

:bug: Fix yaml task data

---

addon/adapter.go

Add support for Adapter.Log to complement addon.Activity.  This provides convenient way for addons to include information in the pod log but not the task activity (which is also logged).  Add writers do not need to construct their own logger.
Used in addons as:
```
addon.Log.Info("Something secret.")
```

:sparkles: add addon Adapter.Log.

---

test/api/importcsv/api_test.go
test/api/importcsv/pkg.go

Fixes failing CI caused by Stakeholders lingering after the import test completes.

:seedling: Clean up stakeholders after Import CSV API test

---

.github/workflows/main.yml
.github/workflows/test-nightly.yml
Makefile
test/api/review/api_test.go

Addressing few issues in Hub API tests execution that cause rare/random failures.
- Force serial API test execution (-p=1,weird: looked like time.Sleep e.g. in importcsv test, continue with other tests while the sleep).
- Run API tests 2x in github action (failure in 1st run means a bug, failure only in 2nd run means likely leftover test data). Together with forcing serial test execution, this should help with test failures debugging.
- Updated data cleanup in Review test.

:seedling: Stabilize API tests

---

assessment/application.go
assessment/archetype.go
assessment/questionnaire.go

This bug was causing the slice of application/archetype assessments to be populated with copies of the last assessment, breaking the assessment status check and likely other things as well.

:bug: Fix loop variable pointer bug in assessment logic

---

.github/workflows/main.yml

In order to run E2E API tests with tackle2-hub API tests on matching branches, adding name of PR branch as a variable passed to CI workflow.
Depends on https://github.com/konveyor/ci/pull/23
Related to https://github.com/konveyor/ci/issues/22 and https://github.com/konveyor/go-konveyor-tests/pull/61

:seedling: Add api_hub_tests_ref to CI on PRs

---

.github/workflows/main.yml

Fixing PR ref used to execute CI tests with up-to-date Hub API tests suite. This issue caused E2E API test failures on recent Hub PRs.

:seedling: Fix PR ref passed to CI

---

api/assessment.go

The `Model()` method on the Assessment resource ignores the RiskMessages and Thresholds fields, but they weren't being updated in the `Omit` call in the update handler. This meant that the fields were getting zeroed out, breaking the risk level calculation. 
Fixes https://issues.redhat.com/browse/MTA-1746

:bug: [MTA-1746] Omit thresholds from assessment update

---

auth/roles.yaml

Partial fix for [MTA-1640](https://issues.redhat.com/browse/MTA-1640).

:bug: [MTA-1640] Remove write perms on Review from migrator role

---

auth/role.go
auth/role_test.go
auth/roles.yaml

The migrator role was not able to access the `targets` resource correctly due to a keyname typo in `roles.yaml`. The incorrectly named `verb` key was ignored by the unmarshaller, which resulted in there being no verbs permitted for the resource. This fixes the typo in the yaml, turns on strict unmarshalling in the `LoadUsers` and `LoadRoles` functions, and then adds a unit test to catch future typos.
The tests will catch key typos, typos in http verbs, and typos in user role mappings.
Fixes https://issues.redhat.com/browse/MTA-1455

:bug: [MTA-1455] Fix typo in tackle-migrator role yaml

---

api/analysis.go
hack/add/analysis.sh

TechDependencies deduplicated with direct taking priority.
The solution is to sort the dependencies with DIRECT first. Then relax the Create() to ignore dups on conflict.
The dependencies are not a memory concern.
fixes: #572

:bug: TechDependencies deduplicated with direct taking priority.

---

api/assessment.go
api/questionnaire.go
assessment/assessment.go

The validator used by Gin will validate nested structs, but will not validate a slice of structs unless the binding field tag specifies the `dive` keyword. This needs to be present on every level of nested slices of structs.
Fixes https://issues.redhat.com/browse/MTA-1349

:bug: [MTA-1349] Fix Questionnaire/Assessment validation

---

assessment/assessment.go
test/api/questionnaire/samples.go

The `required` binding validation can't differentiate an int with value 0 from a value that isn't present. Update `order` fields on questionnaire structs to be represented as a pointer that must not be nil. Also disable `excluded_with` validations that don't work on 0 length slices.

:bug: Questionnaire validation should tolerate `order` fields having value 0

---

tracker/jira.go

* Wrap the http.Client used by the Jira library to always add an Accept: application/json header to requests. This fixes the XML and HTML responses from some endpoints during error conditions.
* Directly use jiraclient.Do method instead of convenience methods to work around library-provided error handling that doesn't work in all cases. This gets rid of vague "inspect response body" errors for failure responses not handled by the library.
* Do our own error handling that catches the response format returned by the `/myself` endpoint and others.

:bug: Improve Jira error handling

---

Dockerfile

This was the simplest way to do it I think, without requiring Makefile updates to pass along build-args and dealing with various values. If you just drop tackle2-seed into the project it won't clone it anymore.

:seedling: If seed dir exists on the filesystem, don't clone it in the dockerfile

---

binding/archetype.go
binding/richclient.go
test/api/archetype/api_test.go
test/api/archetype/pkg.go
test/api/archetype/samples.go

Adding Archetype endpoint to binding and basic API test.
Related to https://github.com/konveyor/tackle2-hub/issues/494

:seedling: Add Archetype to binding and API test

---

tracker/jira.go

Fixes the Jira integration to generate and store a link to the created issue's UI location rather than its API location.
Fixes https://issues.redhat.com/browse/MTA-1883

:bug: [MTA-1883] Jira ticket links should point to UI

---

api/questionnaire.go
assessment/assessment.go

Adds validation to ensure that Questionnaires have at least one section, each section has at least one question, and each question has at least one answer. Fixes a problem where submitting a questionnaire with a question with no answers would break the UI.
Fixes https://issues.redhat.com/browse/MTA-1907

:bug: [MTA-1907] Questionnaires require at least one section/question/answer

---

api/application.go
api/archetype.go
assessment/application.go
assessment/archetype.go
assessment/questionnaire.go

This PR fixes two problems:
1) Application `Risk` and `Confidence` will be `"unknown"` and `0` respectively until all required questionnaires are answered.
2) Answers to archived questionnaires will be ignored while performing the calculation.
Fixes https://issues.redhat.com/browse/MTA-1879

:bug: [MTA-1879] Fix Risk/Confidence calculations to only count responses to required questionnaires.

---

auth/role.go

Fixes https://issues.redhat.com/browse/MTA-1966
The new addon uploading of command output files (also) requires POST and PATCH on files/.

:bug: Fixes addon POST /files failing with 401.

---

addon/task.go

Fix `%s` in logged attach message.  Replace _path_ with _name_ which is more relevant.
```
msg=[addon] Addon attached: %s activity=54 path=/buckets/.file/8a4978b1-69b3-48c8-b98b-5cd6093c3d0d
```
Should be:
```
msg=[addon] Addon attached. ID=433 name=analyzer-lsp.output activity=54
```

:bug: Fix logged attach message.

---

api/application.go
api/archetype.go
api/assessment.go

This is needed to aid UI in computing status for an assessment given a questionnaire is marked as not required. If an assessment exists for an archived questionnaire on an app or archetype, the assessment status is no longer valid & the assessment will need to be filtered from status consideration. 
https://issues.redhat.com/browse/MTA-1956

:ghost: Add questionnare required field to assessment

---

docs/questionnaire-yaml.md

Adding documentation for users to build new assessment questionnaires

:ghost: documentation for the questionnaire yaml to be uploaded

---

assessment/questionnaire.go

- Currently when no required questionnaires exist, archetypes are marked as `assessed:true` which results in additional UI code to rule out this case when calculating status. This PR aims to return `assessed: false` in the case of zero required assessments for an archetype.

:ghost: Change assessed logic for archetypes to handle zero required 

---

assessment/application.go

Prior to this commit, tags that applications inherited due to their archetypes' assessments were categorized as archetype tags rather than assessment tags. This corrects the categorization, and in addition fixes some bugs where tags could be inherited from archived assessments.
Fixes https://issues.redhat.com/browse/MTA-1972

:bug: Treat tags that are inherited from archetype assessments as assessment tags rather than archetype tags

---

assessment/application.go

Prior to this commit, tags that applications inherited due to their archetypes' assessments were categorized as archetype tags rather than assessment tags. This corrects the categorization, and in addition fixes some bugs where tags could be inherited from archived assessments.
Fixes https://issues.redhat.com/browse/MTA-1972

:bug: [Backport][MTA-1972] Treat tags that are inherited from archetype assessments as assessment tags rather than archetype tags (#603)

---

assessment/questionnaire.go

@ibolton336:
> Currently when no required questionnaires exist, archetypes are marked as `assessed:true` which results in additional UI code to rule out this case when calculating status. This PR aims to return `assessed: false` in the case of zero required assessments for an archetype.

:ghost: [Backport][MTA-1973] Change assessed logic for archetypes to handle zero required

---

hack/tool/tackle

Updating "tackle" python CLI to be able export&import Konveyor 0.3 Hub API with pathfinder replacement APIs.
Doesn't mean to be full Hub export, but targeting demo lab data import use-case.

:seedling: Update export/import tool for Konveyor 0.3

---

task/manager.go

Detect resource quota exceeded and leave the task.State=Ready.
closes #625

:bug: Fix Fail when Resource Quota exceeded.

---

hack/tool/tackle

On slow environments or large data, export/import/clean-all CLI commands might take more than token lifetime is (5 minutes), that failed the operation.
Adding automatic token refresh and doing necessary refactoring to make it possible.

:bug: Add Token refresh to export/import CLI

---

api/task.go
api/taskgroup.go
task/manager.go

Fix task group submit.
Update to follow error reporting pattern.

:bug: Fix task group update.

---

hack/tool/tackle

Adding migrationwaves to export/import CLI and cleaning some Ref fields to avoid cyclic dependencies (Waves and Stakeholders).

:sparkles: Update export/import CLI for MigrationWaves

---

api/filter/filter.go
api/filter/parser.go
api/task.go

Support: https://github.com/konveyor/tackle2-ui/issues/1931
Note: UI team requested alias for _queued_ states to be supported in filter.  Ex: `?filter=state:queued`.
closes: https://github.com/konveyor/tackle2-hub/issues/641

:sparkles: Add filter/sort/pagination to /tasks.

---

task/manager.go

Pod snapshot can fail when canceling a task with _damaged_ pod.  As a result, the cancel itself should not fail.
Pods usually damaged beyond use when image pull errors.

:bug: Pod snapshot best effort when canceled.

---

task/manager.go

:bug: Prevent action panic from killing the task manager.

---

auth/builtin.go
auth/builtin_test.go
binding/client.go

fix for issue / #619 
Missing Bearer token return error instead of panicking. 
Also updated [Client.send() method](https://github.com/konveyor/tackle2-hub/blob/main/binding/client.go#L639) to work with bearer tokens.

:bug: token authenticate

---

model/model_test.go
model/serializer.go

Bug: File reaper json query:
```
SELECT count(*) 
FROM `Task` ,json_each(Attached) j0 
WHERE json_extract(j0.value,'$.id')=file.pk
```
not finding references which result in false orphans.
Fix:
Ensure struct tags are honored and preserved by jMap. For Attachments:
```
[
{"Activity":9,"ID":351,"Name":"ssh-agent.output"},
{"Activity":14,"ID":352,"Name":"git.output"},
{"Activity":19,"ID":353,"Name":"windup-shim.output"},
{"Activity":20,"ID":354,"Name":"settings.yaml"},
{"Activity":21,"ID":355,"Name":"konveyor-analyzer.output"},
{"Activity":23,"ID":356,"Name":"konveyor-analyzer-dep.output"}
]
```
MUST be stored as (with lower-case keys):
```
[
{"activity":9,"id":351,"name":"ssh-agent.output"},
{"activity":14,"id":352,"name":"git.output"},
{"activity":19,"id":353,"name":"windup-shim.output"}, …
```

:bug: Fix jMap struct field tags preserved.

---

api/base.go
api/task.go
api/taskgroup.go
migration/v14/model/core.go

Merge Task (kind) data into Task model data.  This is to support defining data properties in the task kind to be inherrited by models. Properties in Task (model) data have priority.
In the interest of keeping models simple, moves TaskGroup.Propagate() to the api.  No need for it to be in the model. To support this, the Merge() method was also moved to BaseHandler as it is used by multiple handlers.
Example:
```
---
kind: Task
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
namespace: konveyor-tackle
name: tech-discovery
spec:
data:
mode:
discovery: true
rules:
labels:
included:
- techA
- techB
```

:sparkles: Merge task (kind) data.

---

api/filter/filter.go
api/sort/sort.go
api/task.go

Fix issues reported [here](https://github.com/konveyor/tackle2-ui/issues/1931#issuecomment-2163782267).
1. sorting seems to work only for `id` field i.e. 
2. filtering not supported for `createUser` and `id` fields( both listed in the enhancement)
3.  application name is missing in the response and in filtering. Filtering by application ID works but this is not so nice.
4. `priority` is missing in the response and in the filtering
5.  for `kind`  the filtering is supported by the server but it seems it's not included in the response
---
Filter and sorting: needed to support GORM join queries which qualifies fields by table.
Example: For a task query joined with application, produces all of the task fields qualified as table.column:
```
SELECT task.id, task.name ...
```
And the (joined) …

:bug: Fix task filtering and sorting.

---

api/base.go
api/task.go
api/taskgroup.go
binding/client.go
binding/task.go
task/manager.go
test/api/task/api_test.go

Adds patch endpoints for:
- /tasks
- /taskgroups
The Update() methods on both Task and Taskgroup support both PUT and PATCH depending on the http method. They also support delegation from Submit() which mainly sets the state=Ready.
Updated to return 202 (accepted) on success.
- put /tasks/:id
- patch /tasks/:id
- put /tasks/:id/cancel
BaseHandler.modBody() removed.
Add patch support to binding client.
Adds API test for task patch.
closes: #661 
closes: #662

:sparkles: Add /tasks patch; return 202 for task actions and updates.

---

hack/tool/tackle

Updating export/import CLI config file parsing to not fail on parsing config file without username or password fields.
Not a blocker, but installations without auth enabled still needed keep username and password fields in config (even with a random content), after this PR they don't have to be there.

:bug: Update export/import CLI no-auth

---

k8s/api/tackle/v1alpha2/zz_generated.deepcopy.go
reaper/bucket.go
reaper/file.go
reaper/ref.go

The default reaper frequency is (1) minute.
The reapers are performing 3-4 queries for every _file_ and _bucket_ evaluated for reaping.  With the addition of attaching files to tasks and task-reports, the number of files has increased substantially.  The current algorithm will run 3-4 queries for each resource evaluated.
For example: A deployment with 2000 analyzed applications can have ~25,000 files.  To evaluate 4 resources for references (Task, TaskGroup, Rule, Target) resulted in 100,000 queries each reaper run.
This PR each run (default: 1/ minute) : 
- FileReaper will run exactly **4** queries. 
- BucketReaper will run exactly **3** queries.

:sparkles: Reaper optimization.

---

task/manager.go

Detect malformed _fqin_ and image pull backoff.  When detected, the task is failed and reported with error and event.
Reported as:
```
events:
- kind: ImageError
reason: ImagePullBackOff
last: 2024-06-27T11:04:14.088026727-07:00
- kind: PodDeleted
count: 1
last: 2024-06-27T11:04:14.126638809-07:00
errors:
- severity: Error
description: 'Container (addon) failed: ImagePullBackOff'
```
Detects:
- CrashLoopBackOff,
- ImagePullBackOff
- CreateContainerConfigError
- InvalidImageName
- CreateContainerError
closes: #677

:bug: Detect image issues.

---

migration/v14/model/core.go

Add index on Task.ApplicationID for better performance of cascade delete.

:bug: Add index on Task.ApplicationID.

---

addon/task.go

Support an addon reporting errors independently of reporting state=Failed.

:sparkles: Support task addon succeeded with errors.

---

addon/task.go

Reverts konveyor/tackle2-hub#681

Revert ":sparkles: Support task addon succeeded with errors."

---

task/manager.go
task/rule.go
task/task_test.go

Fixes a potential concurrency when Manager.findRefs() using the `Cluster` while the Manager is refreshing it.

:bug: add task manager cluster mutex.

---

task/manager.go

Re-apply reverted #678  re-based on current main.

:bug: Detect image issues; reapply pr-678

---

task/rule.go

Log rule match only when matched.

:bug: Log when matched.

---

task/manager.go

Delete orphan pods. Pods orphaned when a task is cascade deleted.

:bug: delete orphan pods.

---

api/analysis.go
api/application.go
api/auth.go
api/base.go
api/batch.go
api/context.go
api/error.go
api/identity.go
api/task.go
api/taskgroup.go
cmd/main.go

The gin HTTP request handler uses a `gin.Context` pool.  The _RichContext_ contains the response body which is passed to the `Render` middle-ware. 
We need to remove the rich context to prevent holding on to memory while the context is in the pool.
_WithContext_ renamed to _RichContext_ for clarity.

:bug: fix memory leak caused by gin context pooling.

---

api/analysis.go

Add Analysis application ref to listed analysis resources.
```
- id: 1
createUser: admin.noauth
createTime: 2024-07-08T21:10:58.827832003-07:00
application:
id: 1
name: Daytrader7
effort: 25000
commit: 42b22a90
```

:sparkles: add application ref to analysis (list) resources.

---

task/manager.go

Report event with reason why pending pod cannot be scheduled.
Not sure if this should be merged (or not). Troubleshooting why k8s won't run a pod seems best investigated by snooping around the cluster.  After all ... pods waiting to be scheduled is anticipated (normal) thing on a busy cluster. 
This PR opened only to (potentially) help with troubleshooting broken CI.  It would be better for the CI test to fetch and log task pods stuck at pending.

:sparkles: Detect and report pending pod unschedulable.

---

assessment/assessment.go
assessment/assessment_test.go

Fixes https://issues.redhat.com/browse/MTA-2286

:bug: [MTA-2286] Don't count autoanswered questions when determining whether an asessement has been started.

---

hack/add/identity.sh

Using the hack/add data is convenient way to populate a new dev environment.  The identity script did not create valid identities.  Fields that needed to change to match current expectations have been made.
Now these identities will show up when they're attached to an application.

:ghost: Update hack add data for identity

---

task/manager.go

Preemption (policy) enabled overwritten by task manager.
The approach is to use the `Select()` to specify the fields included in the `Save()`.
This PR also further restricts what a user can update (patch) on a Ready (submitted) task.
https://issues.redhat.com/browse/MTA-3195

:bug: Preemption (policy) enabled overwritten by task manager.

---

api/task.go

Better support succeeded with errors.
closes #725 
needed by: https://github.com/konveyor/tackle2-ui/issues/1997
Example:
GET /tasks/report/dashboard
```
- id: 7
createUser: admin.noauth
createTime: 2024-07-15T15:35:53.198405073Z
name: Daytrader7.1.windup
kind: analyzer
addon: analyzer
state: Succeeded
application:
id: 1
name: Daytrader7
started: 2024-07-15T15:35:53.514805251Z
terminated: 2024-07-15T15:39:40.54619695Z
- id: 8
createTime: 2024-07-15T18:29:25.26836735Z
name: Daytrader8-
kind: language-discovery
addon: language-discovery
state: Failed
application:
id: 2
name: Daytrader8
started: 2024-07-15T18:29:25.648121267Z
terminated: 2024-07-15T18:29:29.798022283Z
errors: 1
- id: 9
createTime: 2024-07-15T18:29:25.26883083Z
name: Daytrader8-
kind: tech-discovery
addon: tech-discovery …
```

:sparkles: Add task dashboard report.

---

api/analysis.go

Analysis created in a transaction.  More efficient and prevents partial reports.

:bug: Analysis created in transaction.

---

api/application.go
api/archetype.go
api/group.go
api/identity.go
api/migrationwave.go
api/stakeholder.go

When inserting a new record, GORM will also attempt to insert records into tables refered to by many-to-many relationships on the inserted record. This commit attempts to ensure that associations are omitted when inserting records, and then the associations are added to the join tables separately.
Also fixes some spots where the Transaction handler was in the wrong spot in the chain or missing entirely.
Fixes https://github.com/konveyor/tackle2-hub/issues/727

:seedling: Omit associations during Create operations

---

task/rule.go

When a task is preempted, it needs to be postponed for a short duration to prevent thrashing. Since individual tasks may override the _global_ preempt policy, the postpone must happen regardless.

:bug: preempted-postpone even when preemption disabled.

---

api/task.go

https://issues.redhat.com/browse/MTA-3651

:bug: quota blocked tasks should be included in queued.

---

database/driver.go
database/pkg.go

Support multiple DB connections.
Using a custom sqlite driver that is a wrapper around the [_standard_](https://pkg.go.dev/github.com/mattn/go-sqlite3) driver but with a mutex around driver.TX and driver.Stmt as needed.

:sparkles: DB reader/writer mutex.

---

go.mod
go.sum
reaper/task.go
settings/hub.go
task/error.go
task/manager.go

Support pod retention settings.
The current policy is to delete pods as soon as completed (succeed or failed).
Tackle users and support are used to troubleshooting by `oc debug` of the task pods.
To support this, the task manager can terminate containers in pods as needed and defer to the reaper to delete the pods. This would be controlled new settings.  By default succeeded tasks would be retained their pods for 1 minute; failed tasks for 72 hours.
In all cases, failure to terminate running container will fallback to deleting the pod immediately.  The retention is best effort.
Running containers are terminated by `kill -p 1`  This will only work for linux containers.

:sparkles: pod retention.

---

database/db_test.go
database/driver.go
database/pkg.go

Seems the underlying sqlite driver keeps the lock until the connection is closed.
The `Conn` acquires the mutex and holds it until the connection is closed.  The `Tx` and `Stmt` are no longer necessary.

:bug: Fixes database-locked.

---

api/migrationwave.go
cmd/main.go
database/db_test.go
database/pk.go
database/pkg.go
migration/v14/model/core.go
migration/v14/model/pkg.go
model/pkg.go
test/api/migrationwave/api_test.go
test/api/migrationwave/samples.go
test/api/review/api_test.go
test/api/review/samples.go
test/api/ticket/api_test.go
test/api/ticket/samples.go
test/api/tracker/samples.go

Generate primary keys instead of GORM.
This fixes the issue of GORM reusing the highest key after the model with that ID is deleted.
When the PK is 0, GORM assigns the next (highest) ID.
This approach is to assign the ID ahead of time using a pool managed by tackle.

:sparkles: Generate Primary Keys.

---

.github/workflows/main.yml
.github/workflows/test-nightly.yml
Makefile
api/error.go
api/pkg.go
api/service.go
auth/roles.yaml

Add `/services/` endpoint.
Add `/services/kai/*` endpoint reverse-proxy to route defined in KAI_URL. 
Add auth scopes.
Related: https://github.com/konveyor/operator/pull/376

:sparkles: Broker KAI api through hub.

---

settings/addon.go
task/manager.go

To support running the task pods as _AnyUser_ instead of root:
- The task manager needs to no longer RunAs user root.
- The /addon directory needs to be an _EmptyDir_. This is because the addon-analyzer Dockerfile cannot create the /addon directory as owned by the _AnyUser_.

:sparkles: Run task pod as AnyUser.

---

Makefile
database/db_test.go
database/driver.go
database/pkg.go

Fixes: https://issues.redhat.com/browse/MTA-4007

:bug: Support reused connection for better performance.

---

settings/addon.go
task/manager.go

To support running the task pods as _AnyUser_ instead of root:
- The task manager needs to no longer RunAs user root.
- The /addon directory needs to be an _EmptyDir_. This is because the addon-analyzer Dockerfile cannot create the /addon directory as owned by the _AnyUser_.
(cherry picked from commit 8769075b3668ed48ae7fe4214c1c3c0757e386ca)

:sparkles: Run task pod as AnyUser. (#755)

---

database/pkg.go
settings/hub.go

Makes the (max) number of DB connections configurable.  The default=1 which is:
- The safest.
- Most consistent performance (not necessarily the best) on NFS.
- Matches how <=0.5 has always worked.
Increasing max-connections > 1 provides much better throughput on fast filesystems.

:sparkles: Max DB connections setting.

---

Dockerfile

It looks like running as root is failing on minikube (and probably vanilla kubernetes) because there is no /etc/passwd entry to correspond to the UID. This is the source of the current test failures.
https://github.com/golang/go/issues/38599
In a minikube environment the operator runs as UID 1001 and assigns this to the hub as well.
My thoughts on this were that we could:
- Add a /etc/passwd for uid 1001 to cover the default vanilla kube/minikube scenario
- Check in the operator if the operators uid is 1001 and if so set the hub_uid to 0 instead, which I guess mimics the current status quo.
- Find a different way to get the UID in go... (no luck so far and I'd guess if there were an option it would have been mentioned on the issue linked above).
@jortel  also mentioned we could:
- Have …

:bug: Fix running as non-root on vanilla kubernetes

---

api/analysis.go

Updating SQL query for getting TechDependencies to include also dependencies with empty labels (that were not returned before).
Related to https://issues.redhat.com/browse/MTA-4169
@jortel This look to work for me, if there were plans for using `json_` methods (or I missed some unwanted side-effect), I open to another solution.
Example query and results with this change:
```
SELECT * FROM (SELECT d.Provider,d.Name,d.Labels,COUNT(distinct d.AnalysisID) Applications FROM TechDependency d WHERE d.AnalysisID IN (SELECT MAX(ID) FROM `Analysis` WHERE ApplicationID IN (SELECT `ID` FROM `Application`) GROUP BY `ApplicationID`) AND d.ID IN (SELECT `ID` FROM `TechDependency`) GROUP BY d.Provider, d.Name) ORDER BY name COLLATE NOCASE;
java|AdministracionEfectivoGrupo.AdministracionEfectivo-ejb|["konv …
```

:bug: Update analyses/report/dependencies labels query

---

api/task.go
binding/task.go

Added a function for cancelling multiple analyses at once.
Resolves: [tackle2-ui issue #2153]( https://github.com/konveyor/tackle2-ui/issues/2153)

:sparkles: Add bulk cancel functionality for analyses

---

api/task.go
binding/task.go
test/api/task/api_test.go

Update the bulk (cancel) action route to be an action against the collection.  Also, instead of passing a list of IDs in the body, use a filter instead.  This is more flexible and RESTful.
Example:
/tasks/cancel?filter=id:(1|2|3)
/tasks/cancel?filter=application.id:44
/tasks/cancel?filter=kind:analysis,state=Pending
The only downside is the url length may be an issue for many thousands of cancels (by id).  However, I don't see that as a mainstream use-case.  I would think that use-case would be better supported by filtering by other than id.  To cancel all running tasks, an empty filter may be passed.

:sparkles: Support bulk task cancel using filter criteria.

---

api/context.go
database/pk.go
docs/binding.txt
hack/next-migration.sh
migration/v15/migrate.go

Consistently use _any_ keyword.

:ghost: using any instead of interface{} introduced in Go 1.18.

---

settings/hub.go
task/error.go
task/manager.go
task/task_test.go

Both the analyzer and tech-discovery both use the same providers. An extension having compatibility with multiple addons is not a common/mainstream use case. To get around this, we have defined a duplicate set of extensions for each provider. One with compatibility with the `analyzer` addon and the other for the `tech-discovery` addon.
After a recent refactor of the generic extension into multiple extensions (go, python, nodejs), it became obvious that maintain the duplicate set of extensions is painful and likely error prone.
It seems a better approach is to change `Extention.Spec.Addon` to (optionally) define a regex. This approach caters to the mainstream use case that extensions have compatibility with one addon.  It also avoids making the field an _array_ requiring a CRD change. …

:sparkles: Support extenion compat with addon as regex.

---

task/manager.go
task/task_test.go

Missed a validation in https://github.com/konveyor/tackle2-hub/pull/782.

:bug: Extension addon (ref) regex fix.

---

api/analysis.go

Issue Description field might be too short to provide enough information about fixing the issue, appending incident Message to it to make it more useful.
This is more a workaround/quickfix, long-term solution is explained in ticket below and at https://github.com/konveyor/analyzer-lsp/discussions/452
Related to: https://issues.redhat.com/browse/MTA-4421 and Hub version of https://github.com/konveyor/kantra/issues/341

:sparkles: Update Issue Description

---

README.md
reaper/README.md
task/README.md

Replace hard coded settings defaults with link into settings README.

:ghost: Link settings in README files.

---

auth/auth_test.go
auth/builtin.go
auth/request.go

When auth is enabled, the builtin provider is logging all errors (even token not authenticated).  Not authenticating the token is is part of the designed process.  The builtin provider should only log invalid tokens and a higher (level=2) logging level. Tokens not authenticated should only be logged (level=1) when none of the providers can authenticate it.
Spam Example:
```
time=2025-02-06T14:33:58Z level=info msg=[auth] Token
[eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHb1ZGZ3ltY2pCT3Z2eDNtLUFy
CB0YXJnZXRzOmdldCB0YXJnZXRzOnBvc3QgdHJhY2tlcnM6cG9zdCBhcHBsaWNhdGlv
ZXJzOmRlbGV0ZSBzdGFrZWhvbGRlcnM6cG9zdCBwcm9maWxlIGJ1Y2tldHM6ZGVsZXR
XGJEv_63_gL3RezVKBOMI4G_pVXzsNgzSB-aK703RVwfVxZrys2I3z7tA4u2LynMVFTuZ] not-authenticated.
```

:bug: Reduce noise produced by the builtin provider.

---

api/application.go

Currently, the application List endpoint performs a query for each application to fetch the tags.  This does not scale well.  This PR fetches all of the tags into a map keyed by application ID.  Pretty sure this must be similar behavior to the un-correlated subquery done by GORM when pre-loading.
The ApplicationTag (join) models are small so not worried about memory footprint.
This reduced the performance (on my minikube with SSD) from 1.8s => ~700ms with 5k applications which is a 60% performance increase. I would expect a more significant impact on cluster hdd backed file systems.
Roughly related to: https://issues.redhat.com/browse/MTA-4165

:bug: Improved application LIST performance.

---

api/analysis.go

Issue Description field might be too short to provide enough information about fixing the issue, appending incident Message to it to make it more useful.
This is more a workaround/quickfix, long-term solution is explained in ticket below and at
https://github.com/konveyor/analyzer-lsp/discussions/452
Related to: https://issues.redhat.com/browse/MTA-4421 and Hub version of https://github.com/konveyor/kantra/issues/341
https://issues.redhat.com/browse/MTA-4817

:sparkles: [backport] Update Issue Description (#773)

---

api/analysis.go

Adjust effort * number-of-incidents in the SQL instead of when rendering.  This will ensure the effort is adjusted before sorted.
Fixes: https://issues.redhat.com/browse/MTA-4323

:bug: Fix sort on effort for effected applications report.

---

auth/reconcile.go
auth/role.go
auth/users.yaml

There few more mandatory User fields to be setup when auth is enabled, adding those. Or we might update the realm setup to not require it by default.
Fixes: https://issues.redhat.com/browse/MTA-5006

:seedling: MTA-5006 Update auth setup after Keycloak update

---

migration/v16/migrate.go

DropColumn needs to be done BEFORE AutoMigrate() is called.
```
SQLite didn't support ALTER TABLE DROP COLUMN until version 3.35.0 (released in March 2021). 
When you drop a column in SQLite, the database actually:
- Creates a new table without the column, 
- Copies the data over (excluding the dropped column),
- Drops the old table,
- Renames the new one.
During this process, indexes, triggers, constraints, etc., are also reviewed and recreated — but only 
if they are considered to still be valid and relevant.
```

:bug: Fix Tag and TagCategory indexes missing.

---

database/db_test.go
database/pk.go

Updates PK catalog when resources has explicitly assigned ID.
For example when populated for demos using scripts.
Example:
TagCategory:
```
id: 14
name: "Test
```
Tag:
```
id:65
categoryID: 14
```
Unit test updated.

:bug: Updates PK catalog when resources has explicitly assigned ID.

---

api/identity.go
binding/application.go
binding/identity.go
migration/v18/model/core.go
model/query.go
test/api/application/identity_test.go
test/api/identity/api_test.go
test/api/identity/identity_test.go

Add support for default credentials.
Each kind may have a default.  Adds filter function to /identities/ (list) endpoint.
Adds new /applications/:id/identities/:kind endpoint which will include defaults.
The tackle2-addon go.mod needs to be updated to use the new binding.
ref: https://github.com/konveyor/enhancements/pull/223

:sparkles: Add support for default credentials.

---

api/task.go
task/README.md
trigger/application.go

Sort discovery tasks by priority then by label (value).
We'll eventually want to update the `Task` CR in the operator to specify the priority of:
| Name           | Priority |
|--------------------|-------|
| language-discovery | 0     |
| tech-discovery     | 1     |
This will be more robust.
This is what the resources currently look like.
```
[jortel@f35a tackle2-hub][HOST/MAIN]$ oc get tasks -o custom-columns=NAME:.metadata.name,PRIORITY:.spec.priority
NAME                 PRIORITY
language-discovery   <none>     map[konveyor.io/discovery:language]
tech-discovery       <none>     map[konveyor.io/discovery:technology]
```
---
This PR also codifies system priority: 0-9 and user priorities 10+.  Tasks created though the API will be adjusted to ensure they are > 10.  For example: a task …

:ghost: Sort discovery tasks by priority then label.

---

api/identity.go
hack/add/identity.sh
hack/update/identity.sh
test/api/identity/api_test.go
trigger/identity.go

Application discover needs to be triggered when:
-  A directly mapped identity has been updated.
- A _default_ identity has been created/updated and the application does not have one of the same _kind_ directly mapped.

:sparkles: Trigger discovery when default cred is updated.

---

addon/task.go
api/identity.go
binding/application.go
hack/add/identity.sh
test/api/application/identity_test.go
test/api/assessment/api_test.go

Add: /applications/:id/identities to list all identities (including defaults) for all kinds.
Inject default creds in addon adapter Application() method.
Required by: 
- https://github.com/konveyor/tackle2-addon-analyzer/pull/154
- https://github.com/konveyor/tackle2-addon-discovery/pull/19
Incidental: Small refactor/re-org of Application binding for consistency.

:sparkles: Support list all application identities.

---

migration/json/fields.go

Fixes json encoding error for merged task.Data.
POST /tasks succeeded but caused a json encoding error which resulted in no document returned.  This only happens when the task.Data is merged either from a TaskGroup or the Task (CR).Data. 
Not discovered until now because:
- The returned document is not validated by api-tests.
- The UI does not look at returned created tasks until now.
- Developers mostly use YAML.

:bug: No document returned by: POST /tasks with json encoding.
